### ISSUE TITLE
[Feature request] 可输入多行

### ISSUE THREAD

**Issue by sunnylqm** [ddiu8081/chatgpt-demo#10]

**Comment by Mircc** [comment]
对的，目前回车直接发送出去了，可以改为手动发送，或ctrl+回车发送呢

**Comment by TraderGalax** [comment]
赞同

**Comment by XOKP** [comment]
AI的回复似乎也倾向全部挤在同行

**Comment by Limour-dev** [comment]
将src/components/Generator.tsx中的input元素换成textarea后，通过粘贴可以输入换行符，但是直接enter不行

**Comment by Limour-dev** [comment]
修改 e.key === 'Enter' && !e.isComposing && handleButtonClick() 为 
e.ctrlKey && e.key === 'Enter' && !e.isComposing && handleButtonClick() 
可以回车输入换行，然后ctrl+回车发送了

![image](https://user-images.githubusercontent.com/93720049/222875497-3a543137-06ec-479e-bee0-6fed24c40464.png)

**Comment by ddiu8081** [comment]
已加入 Shift+回车换行
