### ISSUE TITLE
OpenAI官方的playground方式可以自由删除对话内容,可以变相的使问答内容持续递进,算是一个比较好的方案

### ISSUE THREAD

**Issue by dckill** [ddiu8081/chatgpt-demo#102]
### Clear and concise description of the problem

因为OpenAI的API限制4096个字符,导致很多问答过程内容占用了很多字符长度, 希望能像官方的这个playground处理方案,可以手动的去除掉一些问题和回复,并且能自动以参数, 这样可以保证总是能在要求的字符数量之内进行滚动回答,算是一种变相的延长获取答案的方法. 

https://platform.openai.com/playground?mode=chat&model=gpt-3.5-turbo-0301

### Suggested solution

能手动取出一些过往的问答内容, 使对话能够持续进行.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Duplicate of #90
