### ISSUE TITLE
[bug] Invalid signature 

### ISSUE THREAD

**Issue by moHaHa** [ddiu8081/chatgpt-demo#117]
### Describe the bug

I'm trying to ask but I got this message 
![image](https://user-images.githubusercontent.com/72744132/222992522-accb6eaa-d7e4-4292-8d95-575d4c6ec79e.png)
 
## request 
```bash
curl 'https://chatgpt.ddiu.me/api/generate' \
  -H 'authority: chatgpt.ddiu.me' \
  -H 'accept: */*' \
  -H 'accept-language: en,en-US;q=0.9,ar;q=0.8' \
  -H 'content-type: text/plain;charset=UTF-8' \
  -H 'cookie: mp_10bab2a6cec3a2ef62083257f3f09083_mixpanel=%7B%22distinct_id%22%3A%20%22186b453fe1d317-0fdc99e75b6021-26031951-100200-186b453fe1e29d%22%2C%22%24device_id%22%3A%20%22186b453fe1d317-0fdc99e75b6021-26031951-100200-186b453fe1e29d%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D' \
  -H 'origin: https://chatgpt.ddiu.me' \
  -H 'referer: https://chatgpt.ddiu.me/' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  --data-raw '{"messages":[{"role":"user","content":"test"},{"role":"assistant","content":"Invalid signature"},{"role":"user","content":"how to say hellow world in js?"},{"role":"assistant","content":"Invalid signature"},{"role":"user","content":"how to log hello world in js ?"}],"time":1678062780713,"sign":"dbbfcb56a7c04cd1136ae30da7283912cd2b21509e02d0b17573f58103cc2b00"}' \
  --compressed
```

## response 
```json
Invalid signature
```

### Reproduction

https://chatgpt.ddiu.me/

### System Info

```Shell
os: windows 
browser: Chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
May cause by #116 (5-minute-validation). 

There may be some problems in different time zones. Rolled back the code for now, I'll confirm later

**Comment by sjdeak** [comment]
Hi @ddiu8081  Could you kindly confirm in [latest docker image release](https://hub.docker.com/layers/ddiu8081/chatgpt-demo/latest/images/sha256-632de99f281a59a74d2ce621b2a485e884d118f1cf00370336ac07fbd152b4ba?context=explore) the issued commit is rollbacked? I deployed it to a US server and make frontend call in CN, met same error message "Invalid Signature" also.

Thanks!

**Comment by ddiu8081** [comment]
> Hi @ddiu8081 Could you kindly confirm in [latest docker image release](https://hub.docker.com/layers/ddiu8081/chatgpt-demo/latest/images/sha256-632de99f281a59a74d2ce621b2a485e884d118f1cf00370336ac07fbd152b4ba?context=explore) the issued commit is rollbacked also? I deployed it to a US server and make frontend call in CN, met same error message "Invalid Signature" also.
> 
> Thanks!

We have fixed the signature failure in docker environment, you can try the latest image.
