### ISSUE TITLE
Code highlighting does not support html

### ISSUE THREAD

**Issue by cokice** [ddiu8081/chatgpt-demo#127]
### Describe the bug

代码高亮不支持html

### Reproduction

代码高亮不支持html

### System Info

```Shell
代码高亮不支持html
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
Currently it should not support GPT to reply directly to HTML code similar to this：

<img width="460" alt="image" src="https://user-images.githubusercontent.com/46418596/223086075-88f2e942-ef95-4871-81d1-403f954612d1.png">



However, if the content of the GPT reply conforms to the Markdown specification, the HTML can be rendered normally：

<img width="747" alt="image" src="https://user-images.githubusercontent.com/46418596/223086451-8688c15a-3bcc-4b9b-9e2a-2003bdd2c2bc.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/46418596/223086491-01fd6312-b530-47d5-8e36-ad4d220ff2d1.png">

**Comment by yzh990918** [comment]
It doesn't match Markdown's plain HTML answer, and the official doesn't seem to have handled it.

**Comment by ddiu8081** [comment]
Might be fixed by #141
