### ISSUE TITLE
回答的问题过长时，页面会发生抖动

### ISSUE THREAD

**Issue by hqw567** [ddiu8081/chatgpt-demo#130]
### Describe the bug

https://user-images.githubusercontent.com/74847198/223034051-a3499c0f-cc66-4558-9e71-503b5816830e.mp4

### Reproduction

回答的问题过长时，页面会发生抖动

### System Info

```Shell
userAgent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hswmartin** [comment]
#107 提了这个pr解决了这个问题

**Comment by ddiu8081** [comment]
Duplicate of #89
