### ISSUE TITLE
需要mt 代码块添加 copy

### ISSUE THREAD

**Issue by Jeffrey-mu** [ddiu8081/chatgpt-demo#131]
### Clear and concise description of the problem

需要mt 代码块添加 copy

### Suggested solution

添加一个复制插件 或者是写一个复制插件 我看markdown-it 包插件市场应该已经有这样的插件了

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Duplicate of #69
