### ISSUE TITLE
添加新的域名访问，网站报错 TypeError: Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by AydenGen** [ddiu8081/chatgpt-demo#134]
### Describe the bug

1. 通过vercel打包生成的vercel域名可正常访问
2. 添加新的CNAME记录，使用新的域名访问报错
` TypeError: Cannot read properties of null (reading 'nextSibling')`
3. vercel域名：https://chatgpt-demo-chi-beryl.vercel.app/
自定义域名：https://chatgpt.white-peach.ga/
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/34738584/223048763-6ed3b7e6-1b1c-4870-9aca-dd64081034ca.png">

### Reproduction

https://chatgpt.white-peach.ga/

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.80 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Firefox: 107.0.1
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xxnuo** [comment]
I had the same issue, but I found a solution by disabling the DNS CNAME Proxy while using Cloudflare DNS. Now it runs correctly.

> 如果你用的是 Cloudflare  DNS，可以直接像我这样关闭你的 [chatgpt.white-peach.ga](https://chatgpt.white-peach.ga/) 的 CNAME 记录里的代理功能就能正常用了。

![dashboard](https://user-images.githubusercontent.com/54252779/223294538-91411677-1c69-4826-8aef-86b24a8b21ef.png)

**Comment by AydenGen** [comment]
> I had the same issue, but I found a solution by disabling the DNS CNAME Proxy while using Cloudflare DNS. Now it runs correctly.
> 
> > 如果你用的是 Cloudflare  DNS，可以直接像我这样关闭你的 [chatgpt.white-peach.ga](https://chatgpt.white-peach.ga/) 的 CNAME 记录里的代理功能就能正常用了。
> 
> ![dashboard](https://user-images.githubusercontent.com/54252779/223294538-91411677-1c69-4826-8aef-86b24a8b21ef.png)

谢谢，解决了

**Comment by pjq** [comment]
赞 同样的问题
