### ISSUE TITLE
用这个方法，3分钟搞定ChatGPT注册

### ISSUE THREAD

**Issue by hardwell391** [ddiu8081/chatgpt-demo#137]
### Clear and concise description of the problem

ChatGPT注册教程：[ChatGPT注册攻略](https://github.com/xiaoming2028/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)

### Suggested solution

ChatGPT注册小窍门：[ChatGPT注册大全](https://github.com/xiaoming2028/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Move to discussions. Issue is used to track issues and submit feature requests.
