### ISSUE TITLE
Add PWA

### ISSUE THREAD

**Issue by hqw567** [ddiu8081/chatgpt-demo#139]
### Clear and concise description of the problem

如题

### Suggested solution

https://web.dev/learn/pwa/

https://realfavicongenerator.net/

https://github.com/vite-pwa/astro

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by nevertoday** [comment]
在这个帖子下， 厚颜无耻的帖一个需求， 能不能：
比如问题是，白宫的网址是多少，答案中有网址的情况，都让对应网址href 到对应网址， 目前全部只是文本而已~

**Comment by imageList** [comment]
Added in https://github.com/ddiu8081/chatgpt-demo/commit/0998579a5c7a6f1168515662717e4cf41973e06c
