### ISSUE TITLE
Stuck in "AI is thinking" on localhost

### ISSUE THREAD

**Issue by wishstrive** [ddiu8081/chatgpt-demo#144]
### Describe the bug

首先感谢您的开源项目。
问题描述：部署到本地，并在配置文件中填写api_key和代理地址后，在localhost一直显示ai正在思考。

### Reproduction

如上

### System Info

```Shell
win10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nevertoday** [comment]
我macos 也是这样，真的爱思考~ 但是我放弃本地 了， 我还是转移到服务器了~

**Comment by wishstrive** [comment]
> 我macos 也是这样，真的爱思考~ 但是我放弃本地 了， 我还是转移到服务器了~

哈哈哈真的爱思考可还行。
我感觉应该是请求没能发出去，因为openai那没显示接收到有taken。
不知道是哪里出问题了

**Comment by lxxxv5** [comment]
openai 接口需要翻墙才能访问，你可以在 env 里设置 HTTPS_PROXY 参数

**Comment by wishstrive** [comment]
> openai 接口需要翻墙才能访问，你可以在 env 里设置 HTTPS_PROXY 参数

嗯，我在env里设置了代理的，但是还是不行

**Comment by danggerenba** [comment]
请问我本地运行后是这样的 是怎么回事 我比较小白 有带梯子的全局环境
<img width="672" alt="image" src="https://user-images.githubusercontent.com/119066997/223164434-bc4cfbea-e874-4160-a2a7-10a0fe20035f.png">

**Comment by Loongphy** [comment]
Since yesterday, the same thing has happened on the deployment on Vercel. It might be the free plan rate limit.

**Comment by guxuerui** [comment]
> > openai 接口需要翻墙才能访问，你可以在 env 里设置 HTTPS_PROXY 参数
> 
> 嗯，我在env里设置了代理的，但是还是不行

理论上来说，打开梯子之后，需要选对合适的节点，因为有的节点不能访问OPENAI的接口，然后在 `.env` 文件里设置好`OPENAI_API_KEY`就可以了

**Comment by wishstrive** [comment]
> 

谢谢回复。我已经被openai给封号了🤣

**Comment by turingcat0101** [comment]
> > 
> 
> 谢谢回复。我已经被openai给封号了🤣

哈哈哈，同惨。启动项目后就正常对话了两次，就再不响应了，然后登录openai网站，提示 `Account deactivated`🤣🤣

**Comment by ddiu8081** [comment]
We've just added a more detailed error message output. You should now be able to see the cause of the error in the UI.

**Comment by nevertoday** [comment]
同喜同贺，我也被ban了
