### ISSUE TITLE
Could you implement "sweetalert" for password protection? 

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#149]
### Clear and concise description of the problem

Actually pass my vercel subdomain to my friends, but I am afraid that more people will access it and take advantage of my key. (take advantage to use a lot and openai charges me a lot.)

### Suggested solution

I would like to share this project working with my chatgt key, but I only want my friends to have access. I think with SweetAlert you can implement passwords.

### Additional context

Could you implement "sweetalert" for password protection? 

I would like to share this project working with my chatgt key, but I only want my friends to have access. I think with SweetAlert you can implement passwords.

Actually pass my vercel subdomain to my friends, but I am afraid that more people will access it and take advantage of my key. (take advantage to use a lot and openai charges me a lot.)

Thanks !

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Yes, password-protecting is important. I would prefer to provide a gateway page as the site entry.

**Comment by Root-FTW** [comment]
> Yes, password-protecting is important. I would prefer to provide a gateway page as the site entry.

That would be great, thank you very much for making it possible, I will keep an eye on your code for when this improvement arrives.

Thank you!

**Comment by ddiu8081** [comment]
Added in #190 .

**Comment by Root-FTW** [comment]
> Added in #190 .

Enter the variable and password in vercel, but it never asks for the password,

**Comment by felipfr** [comment]
> Added in #190 .

Could you suggest some option for user and password registration, with the option of approval by the administrator?

**Comment by Root-FTW** [comment]
> > Added in #190 .
> 
> Could you suggest some option for user and password registration, with the option of approval by the administrator?

This would be great

**Comment by ddiu8081** [comment]
> This would be great

Let's carry it in #201.
