### ISSUE TITLE
EDGE_FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#151]
### Describe the bug

Has anyone found a solution to this problem?

An error occurred with your deployment
EDGE_FUNCTION_INVOCATION_TIMEOUT

My subdomain in vercel was working perfect, I didn't modify anything and suddenly it didn't work anymore.

有没有人找到解决这个问题的办法？

我的vercel子域工作得很好，我没有修改任何东西，突然间它就不工作了。

![2023-03-06 14_25_22](https://user-images.githubusercontent.com/108767514/223260014-a927fa7a-e23c-4e59-8574-1af51550b1a5.png)

### Reproduction

My subdomain in vercel was working perfect, I didn't modify anything and suddenly it didn't work anymore.

### System Info

```Shell
Vercel
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HBO30** [comment]
Related  #153

**Comment by ddiu8081** [comment]
Sorry, we have run out of API Key quota in our demo and can't host any more requests. You may consider self-deployment.

**Comment by Root-FTW** [comment]
> Sorry, we have run out of API Key quota in our demo and can't host any more requests. You may consider self-deployment.

I was using my own api KEY that I am paying for myself, in fact I created another new payment account and still got that error, now it works but I don't know what happened.

**Comment by ddiu8081** [comment]
According to the feedback from the [community](https://community.openai.com/), it seems to have encountered some api exceptions today, and I wonder if this is the reason.

**Comment by Root-FTW** [comment]
> According to the feedback from the [community](https://community.openai.com/), it seems to have encountered some api exceptions today, and I wonder if this is the reason.

At the same time I used my Key in different projects and it works, only in this one it stopped working, last night it worked again, but today again it does not work, but it only happens in this project in other projects where I have the key if it works.

Is it a problem with versel?

**Comment by ddiu8081** [comment]
We've just added a more detailed error message output. You should now be able to see the cause of the error in the UI.

**Comment by CODPHISH** [comment]
我自己写的项目也会时不时出现这问题，不知道咋回事
