### ISSUE TITLE
网页无法进行输出，一直显示AI在思考

### ISSUE THREAD

**Issue by LilQit7** [ddiu8081/chatgpt-demo#154]
### Describe the bug

<img width="789" alt="image" src="https://user-images.githubusercontent.com/45985678/223295990-0ed87cd1-b51f-4434-abb3-d9b3934c5edc.png">

### Reproduction

网站无法回答问题

### System Info

```Shell
网站无法回答问题
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
流量超额了，所以官方demo暂时用不了了，尝试自行部署吧
