### ISSUE TITLE
.env文件添加多个key

### ISSUE THREAD

**Issue by zzzqu** [ddiu8081/chatgpt-demo#156]
### Clear and concise description of the problem

希望可以添加多个key，轮询或者等一个key失效后自动切换

### Suggested solution

如上

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Not plans for now. You can checkout this fork version: [ourongxing/chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel)
