### ISSUE TITLE
POST 500 (Internal Server Error)

### ISSUE THREAD

**Issue by zhao0824** [ddiu8081/chatgpt-demo#161]
### Describe the bug

本地
Generator.tsx? [sm]:53          POST http://localhost:3000/api/generate 500 (Internal Server Error)

### Reproduction

POST http://localhost:3000/api/generate 500 (Internal Server Error)

### System Info

```Shell
Generator.tsx? [sm]:53          POST http://localhost:3000/api/generate 500 (Internal Server Error)
requestWithLatestMessage @ Generator.tsx? [sm]:53
await in requestWithLatestMessage (async)
handleButtonClick @ Generator.tsx? [sm]:30
eventHandler @ dev.js:369
Generator.tsx? [sm]:90 Error: Internal Server Error
    at requestWithLatestMessage (Generator.tsx? [sm]:66:15)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhao0824** [comment]
#157

**Comment by chenchuyin** [comment]
同问题 我正在查看代码

**Comment by ddiu8081** [comment]
According to the feedback from the [community](https://community.openai.com/), it seems to have encountered some api exceptions today, and I wonder if this is the reason. Try to request the OpenAI API directly through the HTTP tool?

**Comment by Dx-hualuo** [comment]
I use localhost:3000 for local access, no error found, but not with nginx reverse proxy, the same error prompted

**Comment by yzh990918** [comment]
Seems to need to open a proxy. https://github.com/ddiu8081/chatgpt-demo/issues/34

**Comment by ddiu8081** [comment]
We've just added a more detailed error message output. You should now be able to see the cause of the error in the UI.
