### ISSUE TITLE
First parameter has member 'readable' that is not a ReadableStream.

### ISSUE THREAD

**Issue by pxf123456** [ddiu8081/chatgpt-demo#163]
### Describe the bug

First parameter has member 'readable' that is not a ReadableStream.

### Reproduction

First parameter has member 'readable' that is not a ReadableStream.

### System Info

```Shell
First parameter has member 'readable' that is not a ReadableStream.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yubo9807** [comment]
#65
