### ISSUE TITLE
Add "Pro Mode"

### ISSUE THREAD

**Issue by ansvver** [ddiu8081/chatgpt-demo#165]
### Clear and concise description of the problem

目前前端只有system 内容，不支持预设上文（如预设多轮”user"和“assistant" 的内容）

### Suggested solution

可以增加多几个前端输入框吗

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Use https://platform.openai.com/playground?mode=chat
