### ISSUE TITLE
Cannot stream output

### ISSUE THREAD

**Issue by FloatFrank** [ddiu8081/chatgpt-demo#166]
### Describe the bug

为什么别人的代码是边计算边输出，我这边是计算完成后才统一输出，这是什么问题
Why the output not display rightly but display over the model caculate

### Reproduction

.

### System Info

```Shell
Centos Stream 9, node 18.4
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lxxxv5** [comment]
用了 nginx 代理吗，可能 nginx 代理配置 proxy_buffering 会把流式传输的特性搞没了

**Comment by FloatFrank** [comment]
> 用了 nginx 代理吗，可能 nginx 代理配置 proxy_buffering 会把流式传输的特性搞没了

谢谢！已解决！
