### ISSUE TITLE
Insert JS using `<script>`

### ISSUE THREAD

**Issue by danggerenba** [ddiu8081/chatgpt-demo#168]
### Clear and concise description of the problem

我想在项目里面引入一个JS文件 我应该怎么做 我发现直接引入无效

### Suggested solution

我想在项目里面引入一个JS文件 我应该怎么做 我发现直接引入无效

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by danggerenba** [comment]
我看.env.example里有相关的配置 但我用Vercel搭建的  没有看到也没有生成 .env 文件

**Comment by ddiu8081** [comment]
You can use either of the following 2 ways:

1. Directly modify the code. You can add `<script>` into `src/layouts/Layout.astro`
2. Use environment variables. If you use Vercel, you can go to `Project settings/Environment Variables`, and set a env named `HEAD_SCRIPTS`. e.g. `<script src="..." />`
    
![ScreenShot 2023-03-07 at 23 21 41@2x](https://user-images.githubusercontent.com/1998168/223466655-df579df5-08ab-4296-bc64-b8dabe6021fc.png)
