### ISSUE TITLE
Insert JS using `<script>`

### ISSUE THREAD

**Issue by danggerenba** [ddiu8081/chatgpt-demo#170]
### Clear and concise description of the problem

您好 请问怎么在这个项目里插入我自己的JS呢 我想插入JS实现权限控制  但我直接<script></script>无效 不太懂这个前端框架

### Suggested solution

您好 请问怎么在这个项目里插入我自己的JS呢 我想插入JS实现权限控制  但我直接<script></script>无效 不太懂这个前端框架

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by danggerenba** [comment]
我看.env.example里有相关的配置 但我用Vercel搭建的  没有看到也没有生成 .env 文件

**Comment by ddiu8081** [comment]
Duplicate of #168
