### ISSUE TITLE
docker镜像错误

### ISSUE THREAD

**Issue by testnet0** [ddiu8081/chatgpt-demo#175]
### Describe the bug

FROM node:18-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src
COPY . /usr/src
RUN npm install
EXPOSE 8000
CMD npm run start -- --port 8000 --host 0.0.0.0
建议改成这个，不然会存在node版本低的问题

### Reproduction

docker

### System Info

```Shell
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y)

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 79.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by apegeek** [comment]
有解决吗？ 我这边运行Docker镜像有粗在静态资源404问题

243.153.105.210/:1 Uncaught TypeError: Failed to resolve module specifier "@vite/env". Relative references must start with either "/", "./", or "../".
43.153.105.210/:559          GET http://43.153.105.210/node_modules/@unocss/reset/tailwind.css net::ERR_ABORTED 404 (Not Found)
343.153.105.210/:1 Uncaught TypeError: Failed to resolve module specifier "@vite/env". Relative references must start with either "/", "./", or "../".
(index):566          GET http://43.153.105.210/@id/astro:scripts/before-hydration.js net::ERR_ABORTED 404 (Not Found)
childrenConnectedCallback @ (index):566
hasAttribute.firstChild.MutationObserver.observe.childList @ (index):566
(index):566 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://43.153.105.210/@id/astro:scripts/before-hydration.js
await (async)
hasAttribute.firstChild.MutationObserver.observe.childList @ (index):566
243.153.105.210/:1 Uncaught TypeError: Failed to resolve module specifier "@vite/env". Relative references must start with either "/", "./", or "../".

**Comment by ddiu8081** [comment]
I'm not sure if your problem has been solved or not because you submitted it in the bug category. If you have some suggestions, you can try to make a pr. Thanks!

**Comment by apegeek** [comment]
建议弄个qq交流群
