### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by ztreble** [ddiu8081/chatgpt-demo#177]
### Describe the bug

I deployed your project on the Singapore server. There is no problem with the local curl. I opened Alibaba Cloud's 3000 port. The following error will be reported during remote access:

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

I tried to synchronize the time, but it didn't work. I used Singapore's proxy service.What shall I do? thank you

### Reproduction

Deploy service and request remotely

### System Info

```Shell
System:
    OS: Linux 4.18 CentOS Linux 8 (Core)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
    Memory: 134.02 MB / 757.20 MB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
I'm sorry I haven't encountered a similar situation. It sounds like the network environment is causing the problem?

**Comment by zhuidreamweaver** [comment]
generate.ts 把这个22行时间判断删掉试试

**Comment by yzh990918** [comment]
Seems to need to open a proxy

**Comment by qgy18** [comment]
@ztreble 打开这个文件  `/dist/server/chunks/pages/all.xxxx.js`

搜索 `digestMessage`，改成：

``` js
async function digestMessage(message) {
  return sha256(message).toString();
}
```

我在本地部署时，必须这么改，否则会因为 `crypto` 未导入直接报错。

**Comment by mdhduwewe** [comment]
> @ztreble打开这个文件 `/dist/server/chunks/pages/all.xxxx.js`
> 
> 搜索`digestMessage`，改成：
> 
> ```js
> async function digestMessage(message) {
>   return sha256(message).toString();
> }
> ```
> 
> 我在本部署时，必须这样改，否则会因为`crypto`未导入直接报错。

这对我有用

**Comment by zhuozhiyongde** [comment]
> @ztreble 打开这个文件 `/dist/server/chunks/pages/all.xxxx.js`
> 
> 搜索 `digestMessage`，改成：
> 
> ```js
> async function digestMessage(message) {
>   return sha256(message).toString();
> }
> ```
> 
> 我在本地部署时，必须这么改，否则会因为 `crypto` 未导入直接报错。

同样对我有用
