### ISSUE TITLE
Create a new `feat/netlify` branch

### ISSUE THREAD

**Issue by yzh990918** [ddiu8081/chatgpt-demo#178]
### Clear and concise description of the problem

I configured the netlify version of the project, help me create  a `feat/netlify` branch first, and then I can submit a PR, Thanks. @ddiu8081 

### Suggested solution

-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
created.

**Comment by yzh990918** [comment]
> created.

Thanks
