### ISSUE TITLE
Unable to use the official demo

### ISSUE THREAD

**Issue by 17736638254** [ddiu8081/chatgpt-demo#179]
### Describe the bug

https://chatgpt.ddiu.me/  这个网站这几天都无法使用，提问题总是提示：在思考

### Reproduction

https://chatgpt.ddiu.me/  这个网站这几天都无法使用

### System Info

```Shell
https://chatgpt.ddiu.me/  这个网站这几天都无法使用
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Lmmmmmm-bb** [comment]
#154
