### ISSUE TITLE
Unable to use the official demo

### ISSUE THREAD

**Issue by suifan** [ddiu8081/chatgpt-demo#181]
### Describe the bug

演示站怎么不能访问了

### Reproduction

演示站怎么不能访问了

### System Info

```Shell
演示站怎么不能访问了
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Duplicate to #154.
