### ISSUE TITLE
服务器上如何部署

### ISSUE THREAD

**Issue by suifan** [ddiu8081/chatgpt-demo#183]
### Describe the bug

服务器上如何部署，可以打包将dist文件夹上传到服务器运行吗，还是需要再服务器上装node环境，用node运行呢。

### Reproduction

服务器如何部署

### System Info

```Shell
服务器如何部署
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Thanks for taking the time to fill out this bug report! Please read this note otherwise your question may be closed directly:

- If the language of the README is English, it is best to use English to ask questions. This allows more people to search and participate in the issue.
- For Q&A, please ask your questions in the discussions and not in the issue, if the repo has Discussions
- Ensure the bug was not already reported by searching on GitHub under Issues.
  If you're unable to find an open issue addressing the problem, open a new one. Be sure to include:
  - A title and clear description.
  - As much relevant information as possible.
  - A code sample or an executable test case.

**Comment by ddiu8081** [comment]
You need a node environment to run it, even if you use the `build` command.

```shell
npm run build
node ./dist/server/entry.mjs
```

Read more on https://docs.astro.build/en/guides/integrations-guide/node/#standalone

**Comment by suifan** [comment]
Thank you. It has been successfully deployed to the server. For the static deployment I use, change the output parameter to static. Online website: guai.org

**Comment by yzh990918** [comment]
You can refer to the documentation：https://docs.astro.build/en/guides/deploy/

**Comment by suifan** [comment]
[lighthouse@VM-4-2-centos server]$ node entry.mjs
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'undici' imported from /www/wwwroot/woss.cc/server/entry.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:908:9)
    at moduleResolve (node:internal/modules/esm/resolve:957:20)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:604:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v17.9.1

Using the method you said, there are errors such as reporting.

**Comment by ufoozhenghao** [comment]
> 

i got the same issue

**Comment by ufoozhenghao** [comment]
> [lighthouse@VM-4-2-centos server]$ node entry.mjs node:internal/errors:465 ErrorCaptureStackTrace(err); ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'undici' imported from /www/wwwroot/woss.cc/server/entry.mjs at new NodeError (node:internal/errors:372:5) at packageResolve (node:internal/modules/esm/resolve:908:9) at moduleResolve (node:internal/modules/esm/resolve:957:20) at defaultResolve (node:internal/modules/esm/resolve:1173:11) at ESMLoader.resolve (node:internal/modules/esm/loader:604:30) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18) at ModuleWrap. (node:internal/modules/esm/module_job:80:40) at link (node:internal/modules/esm/module_job:78:36) { code: 'ERR_MODULE_NOT_FOUND' }
> 
> Node.js v17.9.1
> 
> Using the method you said, there are errors such as reporting.

Cannot find package 'undici' imported

**Comment by JohnnyZhang0628** [comment]
> [lighthouse@VM-4-2-centos server]$ node entry.mjs node:internal/errors:465 ErrorCaptureStackTrace(err); ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'undici' imported from /www/wwwroot/woss.cc/server/entry.mjs at new NodeError (node:internal/errors:372:5) at packageResolve (node:internal/modules/esm/resolve:908:9) at moduleResolve (node:internal/modules/esm/resolve:957:20) at defaultResolve (node:internal/modules/esm/resolve:1173:11) at ESMLoader.resolve (node:internal/modules/esm/loader:604:30) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18) at ModuleWrap. (node:internal/modules/esm/module_job:80:40) at link (node:internal/modules/esm/module_job:78:36) { code: 'ERR_MODULE_NOT_FOUND' }
> 
> Node.js v17.9.1
> 
> Using the method you said, there are errors such as reporting.

+1
