### ISSUE TITLE
Suggestion: Cancel support for httpproxy.

### ISSUE THREAD

**Issue by enhay** [ddiu8081/chatgpt-demo#186]
### Describe the bug

Due to the support for httpproxy which introduces undici and the import { fetch, ProxyAgent } from 'undici', Vercel compilation cannot pass. Although this problem can be solved using the custom plugin Vercel-disable-blocks, there are still compilation issues on other platforms such as Cloudflare. Disabling httpproxy support adds unnecessary complexity to the project. It is recommended that developers use tun models or other methods to solve network problems themselves.

### Reproduction

deploy for cloudflare

### System Info

```Shell
run  pnpm astro add cloudflare  && pnpm run build 
got error 
error:   Could not resolve "async_hooks"
File: node_modules/.pnpm/undici@5.20.0/node_modules/undici/lib/api/api-connect.js:4:34
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Thanks, I did have to do a lot of work as well as encounter as well as a lot of inconvenience because of this feature. I am willing to remove this support.

**Comment by ddiu8081** [comment]
Removed in v2.
