### ISSUE TITLE
Is it possible to add a simple permission control

### ISSUE THREAD

**Issue by WinterChenS** [ddiu8081/chatgpt-demo#19]
现在开放了3.5的api，不进行登录权限的控制，很容易把额度刷完，只需要加一个简单的验证，然后是否可以把部署方式搞到railway里面

**Comment by EasyChris** [comment]
同样有这个需求

**Comment by ddiu8081** [comment]
我计划先加一个 Deploy to Vercel，Railway不知道是否支持 还得研究下

**Comment by fungoindia** [comment]
> 

请问你的服务器是部署在Vercel嘛  刚才我部署Vercel 用Vercel自带的域名打开项目被墙了， 我看你的在国内网都可以正常访问 请问你是部署在那个地区呢

**Comment by WinterChenS** [comment]
@ddiu8081 简单的中间件进行权限的统一控制比较急切，容易被刷流量

**Comment by ddiu8081** [comment]
> > 
> 
> 请问你的服务器是部署在Vercel嘛 刚才我部署Vercel 用Vercel自带的域名打开项目被墙了， 我看你的在国内网都可以正常访问 请问你是部署在那个地区呢

@fungoindia vercel域名会墙，自己绑个域名就行

**Comment by ddiu8081** [comment]
> @ddiu8081 简单的中间件进行权限的统一控制比较急切，容易被刷流量

@WinterChenS 好，会加个简单限制的

**Comment by iLazarus** [comment]
推荐你在前端nginx上加上请求访问控制，不需要改动代码，具体操作请google
一些提示

nginx.conf

```
location xxxx {
    xxxxxxx;
    auth_basic "acces deny!"; 
    auth_basic_user_file passwd.file;
}

```

在nginx.conf所在目录建立文件 passwd.file，这个文件的名字由上文的配置决定
内容
```
admin:401d737d43c046a76967af7eceb4a2b6x23sad
```
401d737d43c046a76967af7eceb4a2b6x23sad 其实就是一个密码的hash

**Comment by XatMassacrE** [comment]
自己部署的话建议用 nginx 做鉴权：

1、首先需要安装nginx的鉴权工具

#### 如果是ubuntu系统
apt install apache2-utils
#### 如果是centos系统
yum install httpd-tools

2、生成鉴权账户

#### 生成的鉴权文件passwd，存放在/usr/local/src/nginx/这个目录里面
htpasswd -c /usr/local/src/nginx/passwd username

3、鉴权
```
server {
    location / {
        auth_basic "auth";
        # auth_basic_user_file鉴权文件位置
        auth_basic_user_file /usr/local/src/nginx/passwd;
    }
}
```

**Comment by meesii** [comment]
我改了一下，增加了一个简单的basic auth，配置到环境变量中就可以了。
[https://github.com/meesii/chatgpt-demo](https://github.com/meesii/chatgpt-demo/commit/be993cc0cc3655ddf374446308ddc6078b3cc2d0)

**Comment by meesii** [comment]
> 

https://github.com/meesii/chatgpt-demo/blob/main/src/layouts/Layout.astro
简单的就在这个文件插入

**Comment by meesii** [comment]
@danggerenba 
https://github.com/meesii/chatgpt-demo/blob/main/src/layouts/Layout.astro
修改这个文件就好了

**Comment by ddiu8081** [comment]
We will follow it in #149 to add a password protection
