### ISSUE TITLE
Please make the text box sticky

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#195]
### Clear and concise description of the problem

When you use the project a lot and scroll the box, the box gets lost and you have to scroll all over again to see the box again.

![2023_03_08_18_05_16](https://user-images.githubusercontent.com/108767514/223897782-a09d8b2f-d532-4050-916f-ad2a9b6cbf4d.png)

![2023_03_08_18_06_05](https://user-images.githubusercontent.com/108767514/223897797-98702d45-7a54-4412-a10d-4b3fc5459aee.png)

### Suggested solution

the solution would be to make that area or text box sticky so that it is always visible to the user and never disappears.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
This doesn't seem to be a problem, as every time a question is asked without a result, the timing of scrolling is triggered based on the gpt reply to the answer.

**Comment by ddiu8081** [comment]
We will follow up on this in #23 .
