### ISSUE TITLE
copy button still dark in light mode

### ISSUE THREAD

**Issue by Loongphy** [ddiu8081/chatgpt-demo#196]
### Describe the bug

The copy button is still dark in the light mode.
![image](https://user-images.githubusercontent.com/42089082/223898027-6213b3f4-ec7a-4f83-9a47-08d9eb7ebc5d.png)

### Reproduction

none

### System Info

```Shell
Browsers: Edge: 110.0.1587.63
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
fixed in #197
