### ISSUE TITLE
output render Markdown

### ISSUE THREAD

**Issue by brandon0824** [ddiu8081/chatgpt-demo#198]
### Describe the bug

When code blocks appear, it is common to have explanations of the code that require rendering with Markdown, such as in the case of "2 3 5 8 12" in the image. Can similar elements be rendered in Markdown mode?
![image](https://user-images.githubusercontent.com/23572851/223909338-04aaab28-1682-442f-97c6-f0941e252912.png)

### Reproduction

deploy on vercel

### System Info

```Shell
deploy on vercel
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
This is exactly the result of the rendering, but the style may be misleading.

**Comment by brandon0824** [comment]
Thanks for your answer.
