### ISSUE TITLE
请问你的服务是搭建在哪上的

### ISSUE THREAD

**Issue by brotherbear2008** [ddiu8081/chatgpt-demo#20]
超级快啊

**Comment by xxyzuo** [comment]
是因为api比较快

**Comment by ddiu8081** [comment]
Vercel US

**Comment by xuxizhen** [comment]
> Vercel US

部署到Vercel，但是提问显示AI is thinking...，是因为什么网络不通吗？还是我key感觉放对了啊，谢谢大佬指导

**Comment by ddiu8081** [comment]
> > Vercel US
> 
> 部署到Vercel，但是提问显示AI is thinking...，是因为什么网络不通吗？还是我key感觉放对了啊，谢谢大佬指导

@xuxizhen 检查下报错日志。如果是自部署的话，需要手动设置环境变量，填入自己的 API key

**Comment by xuxizhen** [comment]
> > > Vercel US
> > 
> > 
> > 部署到Vercel，但是提问显示AI is thinking...，是因为什么网络不通吗？还是我key感觉放对了啊，谢谢大佬指导
> 
> @xuxizhen 检查下报错日志。如果是自部署 Vercel 的话，需要手动在后台设置环境变量

稀里糊涂搞定了，谢谢大佬
https://chatgpt123.fyi/

**Comment by pipdax** [comment]
> 

Setting->environment variables设置了key，但是依然不可以

**Comment by dofine** [comment]
> > 
> 
> Setting->environment variables设置了key，但是依然不可以

我的也是。。已经设置了api，部署在 vercel 上，提示 [POST] /api/generate reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

**Comment by stark-eth** [comment]
> > > > Vercel US
> > > 
> > > 
> > > 部署到Vercel，但是提问显示AI is thinking...，是因为什么网络不通吗？还是我key感觉放对了啊，谢谢大佬指导
> > 
> > 
> > @xuxizhen 检查下报错日志。如果是自部署 Vercel 的话，需要手动在后台设置环境变量
> 
> 稀里糊涂搞定了，谢谢大佬 https://chatgpt123.fyi/

请问代理怎么配置的？

**Comment by Revincx** [comment]
> > > > Vercel US
> > > 
> > > 
> > > 部署到Vercel，但是提问显示AI is thinking...，是因为什么网络不通吗？还是我key感觉放对了啊，谢谢大佬指导
> > 
> > 
> > @xuxizhen 检查下报错日志。如果是自部署 Vercel 的话，需要手动在后台设置环境变量
> 
> 稀里糊涂搞定了，谢谢大佬 https://chatgpt123.fyi/

请问怎么解决的，我这里还是提示 `[POST] /api/generate reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true`
