### ISSUE TITLE
 solid-js: r is not defined

### ISSUE THREAD

**Issue by KinedYK** [ddiu8081/chatgpt-demo#206]
### Describe the bug

Now using node v18.7.0 (npm v8.15.0)
npm run dev
solid.js r is not deined

### Reproduction

r is not defined

### System Info

```Shell
> chatgpt-api-demo@0.0.1 dev
> astro dev

  🚀  astro  v2.1.2 started in 76ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
 error   r is not defined
  File:
    /Users/ykk/MyProject/chatgpt-demo/node_modules/solid-js/web/dist/server.js:297:5
  Code:
    296 |     timeoutHandle = setTimeout(() => reject("renderToString timed out"), timeoutMs);
    > 297 |   });
          |     ^
      298 |   return Promise.race([renderToStream(code, options), timeout]).then(html => {
      299 |     clearTimeout(timeoutHandle);
      300 |     return html;
  Stacktrace:
ReferenceError: r is not defined
    at eval (/node_modules/solid-js/web/dist/server.js:297:5)
    at Module.createRoot (/node_modules/solid-js/dist/server.js:49:14)
    at Module.renderToString (/node_modules/solid-js/web/dist/server.js:294:36)
    at Object.renderToStaticMarkup (@astrojs/solid-js/server.js:16:38)
    at renderFrameworkComponent (/node_modules/astro/dist/runtime/server/render/component.js:178:66)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zyfax** [comment]
Looks like solid-js made an update 2hours ago to version 1.6.13.
It's working on 1.6.12 so I made a change in `package.json` at line 27 as workaround:
From: `"solid-js": "^1.6.11",`
To: `"solid-js": "1.6.12",`

**Comment by yeyinghao** [comment]
> 看起来 solid-js 在 2 小时前对版本 1.6.13 进行了更新。 它在 1.6.12 上工作，所以我`package.json`在第 27 行做了一个更改作为解决方法： 从：`"solid-js": "^1.6.11",` 到：`"solid-js": "1.6.12",`

为啥 1.6.12 还是一样报错

**Comment by elton** [comment]
> Looks like solid-js made an update 2hours ago to version 1.6.13. It's working on 1.6.12 so I made a change in `package.json` at line 27 as workaround: From: `"solid-js": "^1.6.11",` To: `"solid-js": "1.6.12",`

It worked. Thanks!

**Comment by sunht666** [comment]
same question. it worked. thx XD
