### ISSUE TITLE
Storage message history with persistence

### ISSUE THREAD

**Issue by cnericxu** [ddiu8081/chatgpt-demo#21]

**Comment by 18310691938** [comment]
保存上下文这个确实很关键，有时候问着问着报错了，一刷新上下文都没了

**Comment by kydchen** [comment]
迫切的需要这个功能，很多时候一个task需要较长时间完成，需要反复和AI协作进行polish，同时还有其他task并发进行，能有历史对话进行保存和分类太重要了。感恩的心
