### ISSUE TITLE
when I set environment variables in vercel, redeploy is fail.

### ISSUE THREAD

**Issue by zhi-re** [ddiu8081/chatgpt-demo#211]
### Describe the bug

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/45028923/224211598-f475fffe-6439-48be-b157-fbcb8758734c.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/45028923/224212575-be02b8f0-4d96-48ba-9252-d87de5c40da2.png">

if I not set environment variables （HTTPS_PROXY） in vercel, it can redeploy success.

### Reproduction

vercel

### System Info

```Shell
vercel
```

### Used Package Manager

npm

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
The Vercel environment does not support the `HTTPS_PROXY` environment variable, you can simply remove it. We will also remove this variable in the next major update.

Also, I reproduced the bug, but really don't know why it's happening...

**Comment by zhi-re** [comment]
ok,thanks,I not use HTTPS_PROXY.
