### ISSUE TITLE
long conversation advice

### ISSUE THREAD

**Issue by sunht666** [ddiu8081/chatgpt-demo#214]
### Clear and concise description of the problem

With more and more conversations, the request will become slower and slower or even timeout. But I don't want to break the current conversation, so I can't clear the screen directly. Can you delete a few sentences of conversation separately so that the conversation can proceed normally.

### Suggested solution

With more and more conversations, the request will become slower and slower or even timeout. But I don't want to break the current conversation, so I can't clear the screen directly. Can you delete a few sentences of conversation separately so that the conversation can proceed normally.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Thanks, we will follow it in #90
