### ISSUE TITLE
r still not defined

### ISSUE THREAD

**Issue by mushmint** [ddiu8081/chatgpt-demo#216]
### Describe the bug

I tried node.js v18.15, 18.7 and 19.7 but none worked.

### Reproduction

r not defined. consistency issue.

### System Info

```Shell
> chatgpt-api-demo@0.0.1 dev
> astro dev

   astro  v2.1.2 started in 690ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

 error   r is not defined
  File:
    C:\Users\Owner\Desktop\chatgpt-demo-main\chatgpt-demo-main\node_modules\solid-js\web\dist\server.js:297:5
  Code:
    296 |     timeoutHandle = setTimeout(() => reject("renderToString timed out"), timeoutMs);
    > 297 |   });
          |     ^
      298 |   return Promise.race([renderToStream(code, options), timeout]).then(html => {
      299 |     clearTimeout(timeoutHandle);
      300 |     return html;
  Stacktrace:
ReferenceError: r is not defined
    at eval (/node_modules/solid-js/web/dist/server.js:297:5)
    at Module.createRoot (/node_modules/solid-js/dist/server.js:49:14)
    at Module.renderToString (/node_modules/solid-js/web/dist/server.js:294:36)
    at Object.renderToStaticMarkup (@astrojs/solid-js/server.js:16:38)
    at renderFrameworkComponent (/node_modules/astro/dist/runtime/server/render/component.js:178:66)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
Pull the latest code, reinstall the dependencies and try.
