### ISSUE TITLE
Answering html pages contaminates the original web style

### ISSUE THREAD

**Issue by youhunwl** [ddiu8081/chatgpt-demo#219]
### Describe the bug

For example, ask him to answer, write a login page

### Reproduction

none

### System Info

```Shell
browsers
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
fixed.
