### ISSUE TITLE
服务器 POST 500（内部服务器错误）

### ISSUE THREAD

**Issue by zhuidreamweaver** [ddiu8081/chatgpt-demo#221]
### Describe the bug

500 Server Error
generate.ts 把这个22行时间判断删掉试试,
成功解决

### Reproduction

部署到服务器接口500

### System Info

```Shell
System:
    OS: Linux 4.18 CentOS Linux 8 (Core)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
    Memory: 134.02 MB / 757.20 MB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
Seems to need to open a proxy.

**Comment by zhuidreamweaver** [comment]
服务器在日本,可以直接连openai,没开代理
