### ISSUE TITLE
有关于预设角色

### ISSUE THREAD

**Issue by babaohuang** [ddiu8081/chatgpt-demo#226]
### Clear and concise description of the problem

如果需要内置角色，但不需要用户设置，需要修改哪部分代码？

### Suggested solution

或者说用环境变量设置role,可行吗？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
You can set default role value in `src/components/Generator.tsx`:

https://github.com/ddiu8081/chatgpt-demo/blob/9c72f14204ca42c8f04df779f2a7955d60205f00/src/components/Generator.tsx#LL11C23-L11C85

We may not plan to add preset system roles in the near future.
