### ISSUE TITLE
Fix the input box to the bottom

### ISSUE THREAD

**Issue by sunnoy** [ddiu8081/chatgpt-demo#23]
输入能放到下面固定么
建议实现多行输入

**Comment by kollyQAQ** [comment]
复议，现在输入框不能换行，很难受

**Comment by yesmore** [comment]
来了，支持换行，以及自定义key 👉 [https://qa.js.cn/](https://qa.js.cn/)

**Comment by CaiPeterCai** [comment]
> 来了，支持换行，以及自定义key 👉 https://qa.js.cn/

你代码和作者的几乎一模一样（比如generate.js），不标明出处（为什么不用fork）
还把License改成什么gpt哪里有这种License
你也好意思贴什么buy me a coffee

**Comment by yesmore** [comment]
> > 来了，支持换行，以及自定义key 👉 https://qa.js.cn/
> 
> 你代码和作者的几乎一模一样（比如generate.js），不标明出处（为什么不用fork） 还把License改成什么gpt哪里有这种License 你也好意思贴什么buy me a coffee

您说得对

**Comment by ddiu8081** [comment]
Added in v2.
