### ISSUE TITLE
Suggestions on using floating headers and footers during use

### ISSUE THREAD

**Issue by Greysonzs** [ddiu8081/chatgpt-demo#230]
### Clear and concise description of the problem

在日常使用当中 如果将一页回答完了过后 会将顶部顶上去直至看不见 底部也会随之抖动 希望大佬可以修改一下 更新一下 有关锁定顶部以及尾部的两个功能

### Suggested solution

希望在header中以及footer中加入position

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
We will follow up on this request in #23
