### ISSUE TITLE
Need to add a button in the header to clear chat history or go to the bottom

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#236]
### Clear and concise description of the problem

因为在有聊天记录的情况下进入到界面，界面会处于最顶部的位置，此时如果聊天记录比较多，到底部继续聊天，或者是点击清除按钮就有点麻烦

### Suggested solution

需要在头部增加一个清除聊天记录或者到底部的按钮

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
We will follow up on this request in #23 then
