### ISSUE TITLE
免费体验入口

### ISSUE THREAD

**Issue by xutongbao** [ddiu8081/chatgpt-demo#245]
### Clear and concise description of the problem

http://chat.xutongbao.top

### Suggested solution

http://chat.xutongbao.top

### Alternative

http://chat.xutongbao.top

### Additional context

http://chat.xutongbao.top

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Looks like it's not a bug. For Q&A, please ask your questions in the discussions and not in the issue.
