### ISSUE TITLE
vercel无法访问

### ISSUE THREAD

**Issue by jinfagang** [ddiu8081/chatgpt-demo#246]
### Describe the bug

![图片](https://user-images.githubusercontent.com/21303438/224606367-ae93d878-0c02-437f-b43c-8f13404dcd24.png)

### Reproduction

vercel deploy

### System Info

```Shell
windows
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
试试用chrome呢

**Comment by jinfagang** [comment]
https://chatgpt-demo-zeta-amber.vercel.app/

Chrome也一样

**Comment by ddiu8081** [comment]
> https://chatgpt-demo-zeta-amber.vercel.app/
> 
> Chrome也一样

感觉是你本地网络配置问题，我访问这个地址是通的。Vercel 相关域名在国内直接访问是不行的，需要配置代理或绑定域名。

**Comment by jinfagang** [comment]
@ddiu8081 请问一下不能直接访问是啥意思呀，我这目前是科学上网的环境
