### ISSUE TITLE
can not open https://chatgpt.ddiu.me/

### ISSUE THREAD

**Issue by daxwang** [ddiu8081/chatgpt-demo#249]
### Clear and concise description of the problem

can't open the website https://chatgpt.ddiu.me/

### Suggested solution

plz open https://chatgpt.ddiu.me/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
It can be opened, but the key call is oversubscribed and cannot be used temporarily, It is recommended to deploy it yourself.

**Comment by daxwang** [comment]
> It can be opened, but the key call is oversubscribed and cannot be used temporarily, It is recommended to deploy it yourself.
but  i hasn't a openai key. just use this for free
