### ISSUE TITLE
remote access from another computer does not work when I try to expose to network. 

### ISSUE THREAD

**Issue by KhryptorGraphics** [ddiu8081/chatgpt-demo#252]
### Describe the bug

remote access from another computer does not work when I try to expose to network. --host switch does not work.
Which file has the "localhost" string that needs to be changed to 0.0.0.0 so it will work on the network. I found it and edited it before and got it working this way, once before but had to revert my virtual machine image for another reason and lost my edits. 

### Reproduction

npm run dev --hosts doesnt work

### System Info

```Shell
Ubuntu
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Npm will parse any argument you pass to it unless you add a `--` before your arguments.

You can either use `npm run dev -- --hosts` or `npx astro dev --hosts`.
