### ISSUE TITLE
who can provide a free openai api key? 

### ISSUE THREAD

**Issue by daxwang** [ddiu8081/chatgpt-demo#253]
### Clear and concise description of the problem

here somebody provide me a free openai api key? just for a  test chatgpt-demo

### Suggested solution

help

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by bolopendem** [comment]
Nobody will provide you with an API, registering with OpenAI is easier than you wrote here.

**Comment by yzh990918** [comment]
https://github.com/ddiu8081/chatgpt-demo#pre-environment
