### ISSUE TITLE
There is a way to make the model a variable?

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#257]
### Clear and concise description of the problem

There is a way to make the model a variable, in the next few days GPT4 will be released, and I want to use the most powerful version no matter how much it costs.

![2023-03-14 11_04_16](https://user-images.githubusercontent.com/108767514/225097275-f2d398b9-e78c-491b-96be-14c6990abe81.png)

### Suggested solution

make the model a variable

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
If you have the ability to call the GPT-4 model, you can modify the environment variable OPENAI_API_MODEL to change the calling model.
