### ISSUE TITLE
GPT4

### ISSUE THREAD

**Issue by GavenTon** [ddiu8081/chatgpt-demo#258]
### Clear and concise description of the problem

Hey, GPT4 is coming,When can we update .

### Suggested solution

Hey, GPT4 is coming,When can we update .

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
We will update it later.

**Comment by yzh990918** [comment]
Unfortunately, it seems that the GPT4 model cannot be used now, and it is necessary to join the waitlist： https://openai.com/waitlist/gpt-4-api

**Comment by yzh990918** [comment]
If you have the ability to call the GPT-4 model, you can modify the environment variable `OPENAI_API_MODEL` to change the calling model.

**Comment by GavenTon** [comment]
Thx, looking forward to u.

**Comment by JSJohnsonJS** [comment]
条件1：Plus subscribers；
条件2：join the waitlist；
然后修改OPENAI_API_MODEL到gpt-4，就可以了，是这个意思吗

**Comment by morvenhuang** [comment]
What is the OPENAI_API_MODEL if I'm going to use gpt4 api?

**Comment by yzh990918** [comment]
> What is the OPENAI_API_MODEL if I'm going to use gpt4 api?

<img width="302" alt="image" src="https://github.com/anse-app/chatgpt-demo/assets/46418596/da1a349f-850e-4380-8a28-ae090b2aaedb">
