### ISSUE TITLE
where to change the model we ask

### ISSUE THREAD

**Issue by cheniujh** [ddiu8081/chatgpt-demo#260]
### Clear and concise description of the problem

i wanna try other models than the default one

### Suggested solution

what is the place to configure this?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
The V2 version will have.

**Comment by yzh990918** [comment]
You can set `OPENAI_API_MODEL` env to change the model.

**Comment by ddiu8081** [comment]
We will keep up with this request in #257
