### ISSUE TITLE
感觉可以改一下布局

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#264]
### Clear and concise description of the problem

可以改成左右分布的，或者把输入框固定在最下面，发送了消息后直接跳到最新消息那，不然消息多了还得滑下去找输入框
![W6J(X_UQO7{JX8YS~MQDMKK](https://user-images.githubusercontent.com/50036597/225299232-25d689e9-0cb3-4004-b5e1-fbaf45f90e00.png)

虽然现在多了个跳转的箭头

### Suggested solution

可以改成左右分布的，或者把输入框固定在最下面，发送了消息后直接跳到最新消息那，不然消息多了还得滑下去找输入框

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
See #247 , we will launch new ui soon.
