### ISSUE TITLE
Node端 crypto is not defined

### ISSUE THREAD

**Issue by RookieChen4** [ddiu8081/chatgpt-demo#267]
### Describe the bug

![image](https://user-images.githubusercontent.com/30798394/225380292-0ae0d9a3-f737-4ce1-b3ee-77372214b8ae.png)
``` javascript
async function digestMessage(message: string) {
  try {
    if (crypto && crypto.subtle && crypto.subtle.digest) {
      const msgUint8 = new TextEncoder().encode(message)
      const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8)
      const hashArray = Array.from(new Uint8Array(hashBuffer))
      return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('')
    } else {
      return sha256(message).toString()
    }
  } catch (err) {
    console.log(err)
  }
}
```
![image](https://user-images.githubusercontent.com/30798394/225381570-af9dd8fe-5641-464f-86da-f75e6492e321.png)

### Reproduction

生产环境

### System Info

```Shell
win11 node18.15.0 生产环境 本地node有crypto api的 不知道是不是打包的问题
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
refer: https://docs.astro.build/en/reference/cli-reference/#astro-preview

**Comment by ddiu8081** [comment]
fixed. reference #177
