### ISSUE TITLE
Is it possible to have a menu to select the model?

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#268]
### Clear and concise description of the problem

to be able to select the model I want to use in real time

### Suggested solution

have a menu as official chatgpt
![2023_03_15_12_55_41](https://user-images.githubusercontent.com/108767514/225428103-7d98a05e-4762-44c8-bd1f-4974b0928a80.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Added in v2.
