### ISSUE TITLE
Can more than one password be assigned in SITE_PASSWORD?

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#271]
### Clear and concise description of the problem

Can more than one password be assigned?

Currently you can set a password, but sometimes I want to pass my demo to several people just to test it but then no longer have access, is it possible to add more than 1 password in the SITE_PASSWORD vercel variable, so that I can delete them later?

### Suggested solution

to be able to add more than 1 password in the SITE_PASSWORD vercel variable

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
This is too customized requirements, it is recommended to fork the code yourself.

**Comment by Root-FTW** [comment]
Now that I think about it, I think it is impossible to add more than 1 password to the same variable, you could create a new variable for example:

SITE_PASSWORD_DEMO

And when a user visits the site, he/she will be asked for the password and can enter the SITE_PASSWORD or SITE_PASSWORD_DEMO password.

> This is too customized requirements, it is recommended to fork the code yourself.

**Comment by Root-FTW** [comment]
you're right, too bad I don't know how to code, hahaha 

Anyway thanks for replying :)

> This is too customized requirements, it is recommended to fork the code yourself.

**Comment by yzh990918** [comment]
Anyway, thanks for the suggestion.
