### ISSUE TITLE
这个现在是免费体验吗？还是后面也一直免费啊

### ISSUE THREAD

**Issue by nsnsqk** [ddiu8081/chatgpt-demo#273]
### Clear and concise description of the problem

如题，我看demo 体验页，现在是免费，后面不会收费吗？

### Suggested solution

暂无

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
It was before, but the API call was exceeded. It is recommended to read the documentation to deploy it by yourself.

**Comment by nsnsqk** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    但是现在我在这个体验地址上，还可以正常用，正常问答啊
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Evan ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月16日 13:47
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ddiu8081/chatgpt-demo] 这个现在是免费体验吗？还是后面也一直免费啊 (Issue #273)
        
      
    
  
  
It was before, but the API call was exceeded. It is recommended to read the documentation to deploy it by yourself.

**Comment by ddiu8081** [comment]
You may be accessing someone else's self-deployed version, and they are directing the link to this project. You can try to contact the deployer for this information.

Unfortunately, our official demo **chatgpt.ddiu.me** is not available at this time.

**Comment by nsnsqk** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    请问，这个链接https://chatforai.com/，不是你们发布的吗？
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月16日 14:20
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ddiu8081/chatgpt-demo] 这个现在是免费体验吗？还是后面也一直免费啊 (Issue #273)
        
      
    
  
  
You may be accessing someone else's self-deployed version, and they are directing the link to this project. You can try to contact the deployer for this information.
Unfortunately, our official demo chatgpt.ddiu.me is not available at this time.

**Comment by ddiu8081** [comment]
> 请问，这个链接https://chatforai.com/ ，不是你们发布的吗？

这是通过我们的自部署方案生成的站点，API Key 不来自于我们。你可以尝试通过底部的邮箱联系到网站的部署者。

**Comment by nsnsqk** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        好吧，感谢
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月16日 14:37
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ddiu8081/chatgpt-demo] 这个现在是免费体验吗？还是后面也一直免费啊 (Issue #273)
        
      
    
  
  

请问，这个链接https://chatforai.com/ ，不是你们发布的吗？

这是通过我们的自部署方案生成的站点，API Key 不来自于我们。你可以尝试通过底部的邮箱联系到网站的部署者。
