### ISSUE TITLE
Long wait Al is thinking...

### ISSUE THREAD

**Issue by dongmuhds** [ddiu8081/chatgpt-demo#275]
### Describe the bug

Before and after March 15th, the chatgpt-demo response speed that I deployed on Vercel suddenly slowed down, and the time for AI is thinking became longer, but the returned messages (jump out one word at a time)  did not slow down

### Reproduction

I redeployed and changed a key on vercel again, but the problem still exists

### System Info

```Shell
Latest version of vercel deployment
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dongmuhds** [comment]
I deployed the chatgpt of other open source projects on vercel and found this problem. This may be caused by the vercel platform, not this project

**Comment by luoxiaofeng1029** [comment]
我也是,今天变得很慢

**Comment by merore** [comment]
我通过API测试也很慢，挂上代理也慢。从返回信息看是服务负载过高。`That model is currently overloaded with other requests.`

**Comment by dongmuhds** [comment]
Foreign forums show that this problem has been encountered all over the world, but if you apply for the API of the enterprise number, you will find that the API returns quickly
