### ISSUE TITLE
how to view error log in production mode？

### ISSUE THREAD

**Issue by IvanCai** [ddiu8081/chatgpt-demo#277]
### Describe the bug

generate接口响应500，但在docker容器下无法看到对应的错误日志

### Reproduction

 docker

### System Info

```Shell
docker环境
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
We've just added more detailed error message output. You should now be able to see the cause of the error in the UI.

**Comment by IvanCai** [comment]
![image](https://user-images.githubusercontent.com/8352980/225792518-84d9a9b7-a8d6-4848-b0ba-1920ea69ecb6.png)
![image](https://user-images.githubusercontent.com/8352980/225792532-bec18d61-c74a-4377-9dce-4cfdfc70f77f.png)
![image](https://user-images.githubusercontent.com/8352980/225792553-1bc66618-08eb-4993-8a2a-f906c984c209.png)

**Comment by ddiu8081** [comment]
Update your docker image to the [latest version](https://github.com/ddiu8081/chatgpt-demo/pkgs/container/chatgpt-demo) then you can see error logs on UI and console when error 500.
