### ISSUE TITLE
抱歉，我不是很能理解HTTPS_PROXY 字段 可以解答一下吗

### ISSUE THREAD

**Issue by zqq-nuli** [ddiu8081/chatgpt-demo#279]
### Describe the bug

我按照文档的方式部署到了netfily 但是我的/api/generate 请求一直超时，当我尝试阅读代码去解决问题的时候 我意识到似乎是我的PROXY出现了问题，但是我却并不能去解决掉这个问题，请问我是否应该在一台可以访问openai-api的服务器上去部署一套接收/api/generate接口的服务吗还是应该如何处理呢?

### Reproduction

HTTPS_PROXY=http://127.0.0.1:7890

### System Info

```Shell
POST https://chatgpt.dushu.work/api/generate net::ERR_CONNECTION_CLOSED 200
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zqq-nuli** [comment]
我可以确定我的API_KEY是没错的并且有余额的

**Comment by ddiu8081** [comment]
Deploying to Netlify will not use the `HTTPS_PROXY` field. It only takes effect in development mode.

When using `HTTPS_PROXY`, the program will use the HTTP proxy when connecting to the OpenAI service.

And we've just added a more detailed error message output. You should now be able to see the cause of the error in the UI.
