### ISSUE TITLE
能不能加个webapp的功能

### ISSUE THREAD

**Issue by shenwrt** [ddiu8081/chatgpt-demo#285]
### Clear and concise description of the problem

就是苹果手机保存书签到桌面，可以当个独立的app使用，不用通过safari浏览器打开

### Suggested solution

就是苹果手机保存书签到桌面，可以当个独立的app使用，不用通过safari浏览器打开

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Duplicate of #139
