### ISSUE TITLE
The model: `gpt-4-32k-0314` does not exist

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#289]
### Describe the bug

I am trying to use the new GPT4 models, and it does not allow it, for example here I want to use the model with more tokens and more expensive and it does not allow me to do it.

![image](https://user-images.githubusercontent.com/108767514/225982547-2a99b229-e641-4f32-9a14-26614151b434.png)

this is the list of the new models that should be supported:

https://platform.openai.com/docs/models/gpt-4

### Reproduction

uses gpt-4-32k-0314 in the model variable

### System Info

```Shell
vercel
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Root-FTW** [comment]
I forgot to mention that my OpenAI account has access to GPT4 models.

**Comment by yzh990918** [comment]
> I forgot to mention that my OpenAI account has access to GPT4 models.

Sorry, we don't have the ability to call gpt-4, so we haven't tested the results of this model.

**Comment by zqq-nuli** [comment]
我正在尝试去使用4.0的模型 等我消息

**Comment by achieverprince** [comment]
As per this comment it is not released yet
https://community.openai.com/t/how-to-get-access-to-gpt-4-32k/104803

**Comment by faynercosta** [comment]
Hahahaha you must have been granted access on the waiting list.

Did you get this e-mail?

Thank you for joining the waitlist to build with [GPT-4](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/MVJGgZ1BsfVW2Dt9W585KkR9W6fpr4J4Yp-MBN3X6VGV3lSbtV1-WJV7CgGwRW55Kvl152Cs7LW7hp6Tz9fZ8N-W1SmTt4739fxNW3r0NyT7V-6NCN94fQX0MBV2YW2JyN5r4DwN6QW2Nmr798CZ0MlDL4M0HZ9LjW5fDp2-57wsl-W8NQPmC1XK5-wW7qJVwG2t7dXzW5PrjRS8njrJ3VD0N8g5BPFLcVxht-m15J13kN5w6VqGHmTGBW2y74p052BJtCW1f1RDl2kfJLzN7C3sk2nrk-rW3NWm8C38x_48W9kMQQ53sp5wQ38sr1)!
 
To balance capacity with demand, we'll be sending invites gradually over time.
 
While we ramp up, invites will be prioritized to developers who have previously build with the OpenAI API. You can also gain priority access if you contribute model evaluations to [OpenAI Evals](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/MVJGgZ1BsfVW2Dt9W585KkR9W6fpr4J4Yp-MBN3X6VGV3lSbtV1-WJV7CgCrBW34rY_X4X6f37W60h4nT1ypyB-W2cMwjM1GVBD8VxmP363WBPj-W3J5DNL1vDnTdW99PCjW3qrp1lW8CDzJK4hY4wwW6sQCVT2nLH79W2v4P2L672J_4W86wtyc2-4zkYW2931K04Qgn9FW6HCFhV5YK1vCW1MYlDx5KrZt0W3xpZmj75RX0HW1TdRSr4FBj8fW4MqR8C4NlJw5W1RQmHT6BBZ2gW4HD6kq6yqZMzW6PZK4n1gxS65W78Ktps8hVSB13jKX1) that get merged, as this will help us improve the models for everyone.

Once you’re off the waitlist, you’ll receive an email with further instructions on how to get started. We will process requests for the 8K and 32K models at different rates based on capacity, so you can expect to receive 8K access first.

**Comment by achieverprince** [comment]
@faynercosta my bad, didn't read the email fully . you are right.

@Root-FTW hope this cleares your doubt.

**Comment by riteshambastha** [comment]
Got the access after waiting for weeks to get the API access. GPT-4 is working fine, but GPT-4-32K is not available somehow. Is it yet to be released? 

openai.error.InvalidRequestError: The model: `gpt-4-32k` does not exist

**Comment by erbanku** [comment]
> Got the access after waiting for weeks to get the API access. GPT-4 is working fine, but GPT-4-32K is not available somehow. Is it yet to be released?
> 
> openai.error.InvalidRequestError: The model: `gpt-4-32k` does not exist

## Check OpenAI Model Access 
```
curl https://api.openai.com/v1/models -H "Authorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxx" >openai-models-access-$(date +%Y%m%d-%H%M%S).json
```

If you do not have access privilege to `gpt-4-32k`, then you can't use this API key to communicate with the OpenAI `gpt-4-32k` model you can only communicate with models you have access privileges.

**Comment by erbanku** [comment]
> I am also getting same error while invoking API /chat/completions { "error": { "message": "The model: `gpt-4-32k` does not exist", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }
> 
> [platform.openai.com/docs/models/gpt-4](https://platform.openai.com/docs/models/gpt-4) ![image](https://user-images.githubusercontent.com/881066/226320807-f476effa-753f-461b-a3ff-d4a0b282378e.png)
> 
> looks like open ai content team is a head of deployment team

You can check your model access using the command above. https://github.com/ddiu8081/chatgpt-demo/issues/289#issuecomment-1492799060
