### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by Songpenglei123** [ddiu8081/chatgpt-demo#292]
### Clear and concise description of the problem

IPv6 cannot access

### Suggested solution

How to deploy it on the local server and access it with IPv6.

### Alternative

How to deploy it on the local server and access it with IPv6.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
Perhaps you should ask `GPT` to answer this question.
