### ISSUE TITLE
[Feature Request] prompt lists

### ISSUE THREAD

**Issue by xushuang-net** [ddiu8081/chatgpt-demo#294]
### Clear and concise description of the problem

增加一个自定义prompt的配置文件,当配置文件生效则引用配置文件中的prompt,首页不显示自定义prompt的输入框,
如果配置文件中配置为空,则在首先现实自定义框.

### Suggested solution

增加一个自定义prompt的配置文件,当配置文件生效则引用配置文件中的prompt,首页不显示自定义prompt的输入框,
如果配置文件中配置为空,则在首先现实自定义框.

### Additional context

这样可以方便通过自定义的prompt做具有不同性格的AI
方便垂直领域的AI机器人平台.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Duplicate to #133
