### ISSUE TITLE
v2 When will it be online?

### ISSUE THREAD

**Issue by zxitedu** [ddiu8081/chatgpt-demo#298]
### Clear and concise description of the problem

Just want to know when version v2 will be available

### Suggested solution

Just want to know when version v2 will be available

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
Still refactoring, refer: https://github.com/ddiu8081/chatgpt-demo/discussions/247
