### ISSUE TITLE
呢能否提供一下实现模型的文字输入

### ISSUE THREAD

**Issue by yuyebei** [ddiu8081/chatgpt-demo#299]
### Clear and concise description of the problem

能不能提供一下在ChatGPT网页上实现https://chatcat.pages.dev/
上这些模型的输入

### Suggested solution

无

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Limour-dev** [comment]
666

**Comment by ddiu8081** [comment]
I'm not quite sure what specific feature you want. Is it this? #133

**Comment by XHXJ** [comment]
> 我不太确定您想要什么特定功能。是这个吗？#133

![image](https://user-images.githubusercontent.com/41843867/226510890-0089db00-8269-4bf7-86a3-dca6aca36683.png)
演示网站中的预设角色是怎么实现的,是输入了怎样的前置条件,git拉下来后我没看到相关功能,谢谢您.

**Comment by irmowan** [comment]
> > 我不太确定您想要什么特定功能。是这个吗？#133
> 
> ![image](https://user-images.githubusercontent.com/41843867/226510890-0089db00-8269-4bf7-86a3-dca6aca36683.png) 演示网站中的预设角色是怎么实现的,是输入了怎样的前置条件,git拉下来后我没看到相关功能,谢谢您.

这个应该是fork自这个repo的其它人自己实现的。可以用system role的设定来封装预定义好的role。

**Comment by ddiu8081** [comment]
This issue is temporarily closed as we do not know the specific functional requirements.

Feel free to reopen this thread by describing the feature points more clearly, in English if possible.
