### ISSUE TITLE
渲染存在空行

### ISSUE THREAD

**Issue by TOMATOFGY** [ddiu8081/chatgpt-demo#303]
### Describe the bug

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/31461318/226281529-2969a37e-bf27-4957-83e8-4d33cef7d9e6.png">

在某一次更新后，渲染时会出现如图所示的空行

### Reproduction

 chrome、safari、edge 均复现

### System Info

```Shell
bytedance@C02F31JWMD6V ~/.ssh> npx envinfo --system --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) 

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 113.40 MB / 32.00 GB
    Shell: 3.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
It doesn't seem like a bug, because the `li` element is wrapped in a `p` tag, which causes line breaks.
