### ISSUE TITLE
History dialog editing

### ISSUE THREAD

**Issue by daiaji** [ddiu8081/chatgpt-demo#305]
### Clear and concise description of the problem

![图片](https://user-images.githubusercontent.com/25875791/226357582-7b16b71e-7ebb-4c64-83c5-320631a28e37.png)

### Suggested solution

![图片](https://user-images.githubusercontent.com/25875791/226357623-e1f2e16c-3f2c-4020-88fa-2c38910bdeb8.png)

### Alternative

然后能不能只删除之前对话的一部分而不是全部？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by daiaji** [comment]
刷新丢失会话也很难崩。

**Comment by ddiu8081** [comment]
On the official website, modifying history messages regenerates the conversation, which I don't think is a good design and doesn't fit the concept of chat.

I think you should delete the history conversation and ask a new question, or create a new one.
