### ISSUE TITLE
context_length_exceeded

### ISSUE THREAD

**Issue by zdjniubi** [ddiu8081/chatgpt-demo#309]
### Describe the bug

<img width="948" alt="image" src="https://user-images.githubusercontent.com/39577077/226525321-4a12f924-b433-46ed-8899-608e7945eb5e.png">
聊一会就会出现token报错提示，旧版本不会

### Reproduction

production

### System Info

```Shell
18
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Are you having too long a conversation? The error message has been given in the screenshot that the model's maximum context length is 4097 tokens. Please try clearing the history message.

**Comment by zdjniubi** [comment]
怎么删历史message

**Comment by zdjniubi** [comment]
get 感谢大佬

**Comment by lianliankan007** [comment]
I agree with the brother upstairs. If the clean button is used, my browsing history will be lost. I hope to add a function to cache browsing history based on the systeam role ID.

**Comment by iRedScarf** [comment]
I often encounter this problem. I think maybe I can consider setting a context upper limit, or just use Anse instead.
