### ISSUE TITLE
Custom API key

### ISSUE THREAD

**Issue by fwnan** [ddiu8081/chatgpt-demo#31]

**Comment by arpit3043** [comment]
assign me this issue

**Comment by lxxxv5** [comment]
> assign me this issue

Does assigning an issue to someone mean that they are expected to complete that issue?

**Comment by ddiu8081** [comment]
I hope everyone can do this and create a PR. If there is a difficulty, I will solve it in my free time.

**Comment by chenyhd** [comment]
需要留意，一台服务器使用多个key容易触发风控问题导致key被封，或者一个 key 在多个 ip 上使用也容易被封。如果想使用自己的key,建议在自己部署的服务器上使用。既然自己部署的话不如保持目前内置 key 的方式。

否则很有可能出现 key 被封，反而责怪服务端是否动了手脚

**Comment by ddiu8081** [comment]
Added in v2.
