### ISSUE TITLE
Add feature to prevent System Role from clearing

### ISSUE THREAD

**Issue by lonr** [ddiu8081/chatgpt-demo#311]
### Clear and concise description of the problem

Currently, the System Role disappears after the clear button is clicked. Users should be able to choose to keep the System Role settings after clearing the chat.
I'd like to draft a PR.

### Suggested solution

Don't let `clear`  clear the role. let the user do that with an `x` button.

![image](https://user-images.githubusercontent.com/4436034/226791762-d6df4d4e-8725-43f6-a975-4f2e52bd4c58.png)

### Additional context

Another idea I have is also to make the role text box editable when clicked.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by vaynevayne** [comment]
It's too complicated, just keep it simple, for example, click the button, don't clear the role and let the user clear it manually

**Comment by lonr** [comment]
> It's too complicated, just keep it simple, for example, click the button, don't clear the role and let the user clear it manually

You are right. I'll update the proposal as you suggested.

**Comment by ddiu8081** [comment]
pr welcome.
