### ISSUE TITLE
Keeping a constant system prompt

### ISSUE THREAD

**Issue by krish-shahh** [ddiu8081/chatgpt-demo#313]
### Clear and concise description of the problem

Can you show how to make the system role the same in the code? Instead of inputting it each time, there is just a generic system role built into the backend.

### Suggested solution

Can you show how to make the system role the same in code? Instead of inputting it each time, there is just a generic system role built into the backend.the 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
I suspect this may be a duplicate question. Does #290 solve your question?
