### ISSUE TITLE
Enter will interrupt the input in Safari

### ISSUE THREAD

**Issue by 880802ll** [ddiu8081/chatgpt-demo#317]
### Additional context

在输入框中回车发送时，如果使用的是Chrome浏览器是正常的，但是在Safari浏览器中，如果使用中文输入法，想用回车选择成英文字母的时候，会直接发送出去，而不是让我能够继续输入。请测试修复。

**Comment by yzh990918** [comment]
Fixed in https://github.com/ddiu8081/chatgpt-demo/commit/7fc87537eef8a1be6ab6f18c38cb9b7c8a6b0cd3
