### ISSUE TITLE
Ability to disable message history

### ISSUE THREAD

**Issue by erbanku** [ddiu8081/chatgpt-demo#318]
### Clear and concise description of the problem

Disable message history of decreasing the mass usage of API tokens.

### Suggested solution

Ability to disable via an environment variable.

### Alternative

Let me know how I can achieve this via changing code (thx, btw)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by lxxxv5** [comment]
You can just click the clean button.

**Comment by erbanku** [comment]
> You can just click the clean button.

The desired effect is to clear the history of refreshment, not only by the clean button.

**Comment by ddiu8081** [comment]
The UI we initially provided was designed to be minimalistic and not able to carry this feature. We will add it in V2. See #247.

**Comment by ddiu8081** [comment]
Added in v2. You can select 'Single Conversion' type to disable chat history.
