### ISSUE TITLE
设定的分享

### ISSUE THREAD

**Issue by yuyebei** [ddiu8081/chatgpt-demo#319]
### Clear and concise description of the problem

我在chatcat上看到很多不同角色，我看到网站上写了prompt有分享，我不清楚prompt是不是就是角色的设定，不过我没能找到它们（在链接上的猫娘讨论里我只找到了魅魔和爱生酱）。如果您能告诉我哪里能找到演示角色们的设定我将感激不尽

### Suggested solution

五

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
你访问的可能是其他人fork并修改过的版本。这个仓库为项目原始仓库，并不包含role设定功能，全部功能即为官方demo连接 https://chatgpt.ddiu.me/ 中所示。 你可以尝试联系这个魔改版本的作者。
