### ISSUE TITLE
After deploying, I don't know how to open the website

### ISSUE THREAD

**Issue by Simon-Yi** [ddiu8081/chatgpt-demo#323]
### Describe the bug

![微信截图_20230326142418](https://user-images.githubusercontent.com/124592768/227759290-be897a02-5d63-4451-a813-73cd985bb88c.jpg)

### Reproduction

After deploying, I don't know how to open the website

### System Info

```Shell
Syetem:debian
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
If you are deploying locally, open the link on the terminal output.
If it's on a server, you should use `pnpm run dev --host` to allow external access, or run in production mode:

```
pnpm run build
node ./dist/server/entry.mjs
```
