### ISSUE TITLE
可以根据自己所在地区选择api服务器地址吗?

### ISSUE THREAD

**Issue by yantoumu** [ddiu8081/chatgpt-demo#324]
### Clear and concise description of the problem

问了下chatgpt
OpenAI API 的节点有多个，分别位于不同的地理位置。除了 https://api.openai.com 这个节点之外，还有以下节点可供选择：

https://api.us-west-2.openai.com: 位于美国西部 2 区域。
https://api.us-east-1.openai.com: 位于美国东部 1 区域。
https://api.eu-gb.openai.com: 位于欧洲伦敦地区。
https://api.ap-southeast-1.openai.com: 位于亚太东南 1 区域。
你可以根据自己所在地区的网络情况，选择离自己最近的节点来访问 OpenAI API，以获得更快的响应速度。

### Suggested solution

直接修改OPENAI_API_BASE_URL= 成上面的地址的话会出现TypeError
fetch failed
cause: Error: getaddrinfo ENOTFOUND api.ap-southeast-1.openai.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'api.ap-southeast-1.openai.com'
  }
}
这样的错误,他们的调用方式不一样吗?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
No, there is no documentation so far that these URLs exist. ChatGPT may occasionally generate incorrect information.

**Comment by ddiu8081** [comment]
This may not be relevant to this project, but you can try visiting https://api.openai.com and several other links. You will find that only the main domain name is present.
