### ISSUE TITLE
code copy is invalid

### ISSUE THREAD

**Issue by Jratil** [ddiu8081/chatgpt-demo#328]
### Describe the bug

ask to write code fragment, but the button of copy is invalid 
![image](https://user-images.githubusercontent.com/29191680/228124957-6776193c-d910-4de3-8588-94010a466f89.png)

### Reproduction

ask: 使用kotlin编写一段冒泡排序

### System Info

```Shell
linux x64
edge 111.0.1661.54
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
It seems works fine. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/46418596/228129552-2a7dfb65-d849-4c0d-b85d-51cd9b21c8cf.png">
