### ISSUE TITLE
hope to use  headless browser to request gpt-4

### ISSUE THREAD

**Issue by vaynevayne** [ddiu8081/chatgpt-demo#330]
### Clear and concise description of the problem

now , you can use chatGpt-4 in office website, if we use headless browser  to mook request ,we can use chatgpt-4

### Suggested solution

create a new  backend project or  find a already exist project

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
This may violate the [TOS of OpenAI](https://openai.com/policies/terms-of-use). I probably won't add this feature.
