### ISSUE TITLE
自定义域名之前访问一切正常的，今天突然进不去了

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#333]
### Describe the bug

然后检查了下问题，好像是vercel部署要改域名的DNS了，

![image](https://user-images.githubusercontent.com/50036597/228833215-81060259-a823-4b21-9ee3-9ac5292d5b69.png)

之前没改过东西，是我的问题，还是都需要改了？

### Reproduction

1

### System Info

```Shell
1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
This does not seem to be relevant to this project, so I will close it. 

You can refer to the documentation or go to the help center about binding domains in Vercel.

Related: https://vercel.com/docs/concepts/projects/domains/add-a-domain
