### ISSUE TITLE
When I was deployed and started using the function, I found that ChatGPT reply messages were not printed consecutively, but all at once

### ISSUE THREAD

**Issue by ZhangzhiqiangGitHub** [ddiu8081/chatgpt-demo#335]
### Describe the bug

When I was deployed and started using the function, I found that ChatGPT reply messages were not printed consecutively, but all at once。

I used the nginx proxy for forwarding, and here is my configuration
<img width="964" alt="image" src="https://user-images.githubusercontent.com/13249968/229009673-42fc435f-bf6f-4782-88ad-32189da1c38a.png">

### Reproduction

no

### System Info

```Shell
Runs on Linux and is accessed by Google Chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
May answer this in #166.

**Comment by ZhangzhiqiangGitHub** [comment]
thank you
