### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#338]
### Describe the bug

突然显示了这个我去查账户余额还有十几美元，然后我从新创建了一个APIkey，从新部署了网站，去看新的API，显示没有被调用，感觉不是没钱了的问题啊

### Reproduction

1

### System Info

```Shell
1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
If you are a non-paying account, the $18 free credit usually expires on April 1, so check your usage page.

**Comment by 0000070** [comment]
> 

为何非付费帐户的api在第三方网站依旧可用呢

**Comment by 1592363624** [comment]
> > 
> 
> 为何非付费帐户的api在第三方网站依旧可用呢

不能把 试了几个不行

**Comment by luoxiaofeng1029** [comment]
变更完环境变量后重启一下你的项目

**Comment by sfw222** [comment]
> If you are a non-paying account, the $18 free credit usually expires on April 1, so check your usage page.如果您是非付费帐户，则 18 美元的免费额度通常会在 4 月 1 日到期，因此请查看您的使用页面。

我刚刚通过vercel部署的，它还显示我限额已用尽。实际上这是我第一次用api的。

**Comment by ddiu8081** [comment]
> > If you are a non-paying account, the $18 free credit usually expires on April 1, so check your usage page.
> 
> 我刚刚通过vercel部署的，它还显示我限额已用尽。实际上这是我第一次用api的。

进OpenAI后台查看下额度，免费账号的额度不是永久有效的，第一批账号额度4月1号就到期了。

**Comment by 1592363624** [comment]
那是因为免费账号额度到期问题，现在有没有好的位置充值了，淘宝都找不到相关服务=.=

**Comment by 1592363624** [comment]
那是因为免费账号额度到期问题，现在有没有好的位置充值了，淘宝都找不到相关服务=.=

**Comment by sfw222** [comment]
> > > If you are a non-paying account, the $18 free credit usually expires on April 1, so check your usage page.
> > 
> > 
> > 我刚刚通过vercel部署的，它还显示我限额已用尽。实际上这是我第一次用api的。
> 
> 进OpenAI后台查看下额度，免费账号的额度不是永久有效的，第一批账号额度4月1号就到期了。

原来是这样啊，非常感谢！
