### ISSUE TITLE
️OpenAi server response error Error: 429:Too Many Requests

### ISSUE THREAD

**Issue by smdyskd** [ddiu8081/chatgpt-demo#343]
### Describe the bug

输入回答就只有️OpenAi server response error Error: 429:Too Many Requests这句话，等了12多个小时了还是这样

### Reproduction

️OpenAi server response error Error: 429:Too Many Requests

### System Info

```Shell
️OpenAi server response error Error: 429:Too Many Requests
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by smdyskd** [comment]
现在直接是无法输入了，聊天框输入后没有反应了

**Comment by Xueshen6** [comment]
> 

应该是api调用格式改变了

**Comment by yzh990918** [comment]
It seems works fine. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by smdyskd** [comment]
> > ![image](https://user-images.githubusercontent.com/129708907/229514785-308d236d-2f57-4225-835d-b4483e9ca46b.png) 目前在这个页面，我按send键完全没反应，无法发送
> 
> 哇！这个UI不错，可以给个链接么？🥲 想改一下页面风格

https://chatcat.pages.dev/ 用的别人现成的，但是我目前无法发送任何问题，你可以帮我看下

**Comment by Xueshen6** [comment]
> 

现成的，能分享一下GitHub链接吗

**Comment by smdyskd** [comment]
> > 
> 
> 现成的，能分享一下GitHub链接吗

这个我也没有，复制别人的

**Comment by erbanku** [comment]
> > > ![image](https://user-images.githubusercontent.com/129708907/229514785-308d236d-2f57-4225-835d-b4483e9ca46b.png) 目前在这个页面，我按send键完全没反应，无法发送
> > 
> > 
> > 哇！这个UI不错，可以给个链接么？🥲 想改一下页面风格
> 
> [chatcat.pages.dev](https://chatcat.pages.dev/) 用的别人现成的，但是我目前无法发送任何问题，你可以帮我看下

一般这种情况可能是因为` API Key `被封了，你试着登陆一下对应` ChatGPT 官网`吧，看看能不能登录。

**Comment by smdyskd** [comment]
> > > > ![image](https://user-images.githubusercontent.com/129708907/229514785-308d236d-2f57-4225-835d-b4483e9ca46b.png) 目前在这个页面，我按send键完全没反应，无法发送
> > > 
> > > 
> > > 哇！这个UI不错，可以给个链接么？🥲 想改一下页面风格
> > 
> > 
> > [chatcat.pages.dev](https://chatcat.pages.dev/) 用的别人现成的，但是我目前无法发送任何问题，你可以帮我看下
> 
> 一般这种情况可能是因为`API Key`被封了，你试着登陆一下对应` ChatGPT 官网`吧，看看能不能登录。

我看下了我的API好像免费流量4月1号过期了，是不是因为这个原因无法使用

**Comment by erbanku** [comment]
是的，过期了就不能用了。

**Comment by smdyskd** [comment]
> 是的，过期了就不能用了。

好的，那我之后尝试续费
