### ISSUE TITLE
This model's maximum context length is 4097 tokens.

### ISSUE THREAD

**Issue by z50913** [ddiu8081/chatgpt-demo#345]
### Clear and concise description of the problem

context_length_exceeded
This model's maximum context length is 4097 tokens. However, your messages resulted in 7752 tokens. Please reduce the length of the messages.

### Suggested solution

如何解除限制呢，同一个ip就没法使用了，是要删除项目里的缓存么，如果可以的话那要如何删除？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
All chat logs exceed the api's maximum limit, you can click the clear button to clear the history.

![ScreenShot 2023-04-04 at 10 40 07](https://user-images.githubusercontent.com/1998168/229672914-a2544904-fd65-4f02-b247-08d03f867fd3.png)

**Comment by z50913** [comment]
okk, I can continue using it
