### ISSUE TITLE
feature request, openai API proxy.

### ISSUE THREAD

**Issue by yunhaizhu** [ddiu8081/chatgpt-demo#351]
### Clear and concise description of the problem

any idea to provide OPNAI API proxy within this server?

### Suggested solution

may merge some api http proxy service within server. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
We already have `OPENAI_API_BASE_URL` environment variable, you can set a proxy-server in self-deployed site.
