### ISSUE TITLE
The HTTPS_PROXY configuration is not effective when deploying the project using Docker.

### ISSUE THREAD

**Issue by oishiimikan** [ddiu8081/chatgpt-demo#353]
### Describe the bug

我的linux系统配置了clash代理，能够连接到openai:
![屏幕截图 2023-04-06 130505](https://user-images.githubusercontent.com/94225870/230278554-249132f2-a7a7-474f-83c2-6a0c4688a366.png)
但是使用docker部署项目且配置HTTPS_PROXY选项好像失效了。服务端出现了超时错误：
![屏幕截图 2023-04-06 130802](https://user-images.githubusercontent.com/94225870/230278973-01dd2aa1-c7a5-4566-8458-e8ab25790ff3.png)
docker-compose.yml配置文件如下：
![屏幕截图 2023-04-06 130553](https://user-images.githubusercontent.com/94225870/230279087-5a5181bf-c3c5-45b4-9f85-c09024109a89.png)
.env配置文件如下：
![屏幕截图 2023-04-06 130718](https://user-images.githubusercontent.com/94225870/230279188-eb18fca4-53b2-4308-86dd-9920b74d72a1.png)

### Reproduction

Timeout errors still occur even after configuring the HTTPS proxy.

### System Info

```Shell
--system
    os: centos7.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
It seems that Docker can't read environment variables successfully. Track in this issue #297.
