### ISSUE TITLE
Can't access by `127.0.0.1:3000`

### ISSUE THREAD

**Issue by danggerenba** [ddiu8081/chatgpt-demo#355]
### Describe the bug

<img width="636" alt="image" src="https://user-images.githubusercontent.com/119066997/230411078-42fad3e7-62b9-458d-8d2c-a46869673971.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/119066997/230411689-e0632057-2a36-4929-b3dc-465be6d44c70.png">
我防火墙什么的都正常 因为我在PHP环境下 localhost能够和127.0.0.1相互转换
但这个项目就不能转换 如果是这个项目本身的配置问题 我如何去修改

### Reproduction

 如果是这个项目本身localhost和127.0.0.1存在配置问题 我如何去修改

### System Info

```Shell
<img width="330" alt="image" src="https://user-images.githubusercontent.com/119066997/230411689-e0632057-2a36-4929-b3dc-465be6d44c70.png">
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
The default dev host is `localhost` only, not `127.0.0.1`.
If you want to set more hosts including `127.0.0.1`, use `--host` flag.

```
npm run dev --host
```

Reference: https://docs.astro.build/en/reference/cli-reference/
