### ISSUE TITLE
nginx idea

### ISSUE THREAD

**Issue by draftpaperkw** [ddiu8081/chatgpt-demo#357]
### Describe the bug

该如何用nginx 代理这个网页？如果直接写会有卡顿。

### Reproduction

Nginx idea

### System Info

```Shell
--Browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chenyhd** [comment]
Here is an example, `proxy_buffering` is the key point
```
location / {

                proxy_pass http://{IP}:3000/;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                client_max_body_size    10m;
                proxy_buffering off;
                gzip off;
        }

```
