### ISSUE TITLE
can I change my gpt3.5 api into chatgpt API in this demo？

### ISSUE THREAD

**Issue by michael7908** [ddiu8081/chatgpt-demo#359]
### Clear and concise description of the problem

According to Readme,  the API behind this demo website is 3.5 turbo version which is much more expensive than ChatGPT API so where I can change this setting to save money? Thank you.

### Suggested solution

According to Readme,  the API behind this demo website is 3.5 turbo version which is much more expensive than ChatGPT API so where I can change this setting to save money? Thank you.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
Of course, you can fork the project yourself to make changes.

**Comment by ddiu8081** [comment]
See #330.

The API used by the ChatGPT website is not publicly available. Using it would violate the [TOS of OpenAI](https://openai.com/policies/terms-of-use). So we do not plan to include this feature. You can fork and edit it.
