### ISSUE TITLE
V2 version's discussion and suggestions

### ISSUE THREAD

**Issue by luoxiaofeng1029** [ddiu8081/chatgpt-demo#364]
### Describe the bug

Where should I submit suggestions and bug reports for V2 version, here or somewhere else? Also, can V2 version be deployed directly on Vercel like V1 version? I couldn't find any tutorial

### Reproduction

none

### System Info

```Shell
none
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
You can directly submit them here, just state in the title or description that it is version v2.

And v2 can be self-deployed like v1, we are working on the documentation for it, which will be published in a few days.

**Comment by enhay** [comment]
v2版本看起来还有不少兼容性的bug,目前测试只有chrome新版本是ok的，在coloros 13的手机自带浏览器，360急速，夸克等浏览器下 聊天区不显示，按钮也没反应。

**Comment by enhay** [comment]
另外默认enter是换行 ctrl+enter是发送是否有点反直觉，感觉多数时候并不需要换行。

**Comment by yzh990918** [comment]
> 另外默认enter是换行 ctrl+enter是发送是否有点反直觉，感觉多数时候并不需要换行。

If you think enter sends, shift + enter wraps better, we will change it later.

**Comment by Ekarmore** [comment]
可以给输入框添加快速切换到输入状态的快捷键，比如`'/'`或者其它键位。

**Comment by enhay** [comment]
个人站点chatcat001.zhaoyoung.me从最早使用的main分支(v1)本周改成了v2(beta)，也收到了一些反馈。由于站点特色，所以对v2的建议更多是从用户沉浸感出发。

初始会话交互

- 当会话列表存在时，页面默认不是第一次或最后一次的会话或第一条，而是新建一条。我修改的方式是不选中会话直接报错提示。
- 移动端设置不明显，用户只有在第一次输入后才会注意到上面的两个按钮。个人最喜欢beta.character.ai的UI交互。
- 界面过于简洁，连header和footer都干掉了，至少留个显眼的位置放你们的项目标识吧

消息的处理过于粗暴

- 对于单次会话，我认为目标应该是为了省token，现在单次会话每次清除历史记录，那么会话列表的意义何在。
- 设置中有maxtoken的配置，但连续会话会回传所有历史消息。会话历史消息当前又不可删除，聊着聊着就超了。我的改动是根据maxtoken动态评估只传输最近的几条消息给API。

pormpt功能缺失

- GPT会话质量很大程度上受限于给出的prompt提示。我看到一些比chatgptdemo丑的多的项目因为好的prompt管理而被很多人使用。v2代码有systemsRole的配置，但是完全没有实现。我的做法是在iconList的下面添加一个textarea来为每个会话预设prompt。

取消API端点

- 我知道有太多的issue询问为什么接口报错，但在当前网络条件下，删除API端点，放弃serverless机房的优势，把网络问题简化为用户自身问题，至少在有大量稳定的openapiproxy前并不能减少issue。也丧失了SSR的优势。我的做法是简化和保留API/general，给用户多一个选择。

代码

- v1代码干净清晰是不可多得的学习solidjs+astro+unocss的好项目，v2可能由于后期规划吧，模块拆分很细，技术选型偏向求新。个人觉得有些炫技了。

历史会话管理

- 有了会话存档，基于历史会话的功能和快捷指令也可以纳入考虑，比如导入导出。还有一些有意思的玩法，比如编辑历史会话伪造上下文。快捷指令/resest清除上下文，/savepoint会话存档，/backtrack会话回溯等都可以丰富功能。

社群

- 提issue成本太高了，建议提供QQ或者T.me群组，方便实际使用的用户反馈。也方便获取赞助，毕竟开源不易，纯爱走不远。

最后感谢作者付出，我个人深知开源不易，无耻的闭了。

**Comment by ddiu8081** [comment]
> 个人站点chatcat001.zhaoyoung.me从最早使用的main分支(v1)本周改成了v2(beta)，也收到了一些反馈。由于站点特色，所以对v2的建议更多是从用户沉浸感出发......

@enhay 感谢细致的体验和建议！我分别回下：

#### 初始会话交互

前两点建议，我们对于首页后续的规划是做一个类似于 VSCode 开始界面的视图，可以展示近期会话和快速创建新会话，让首页不那么空，也无需跳转至侧边栏。

至于界面过于简洁的问题，我们也考虑把欢迎界面做成类似于 v1 的版式，具体放多少东西看后续的把控和实现了。

#### 消息的处理过于粗暴

单次对话的设计是：每次对话会清空上一轮对话内容，但会保留 systemRole 和手动 mock 的消息，这部分还没有实现。

对于回传消息会超限的问题，我暂时没有规划，只传输最近几条消息可能还是会影响回复准确度的。

#### prompt功能缺失

在设计上有单次对话设置的概念，可以传 systemRole 和手动 mock 的消息，不过目前还在寻找合适的位置放这个功能，计划会放在修改会话的弹窗/header/右侧侧边栏中。

#### 取消API端点

server 端请求是会有的，也在正式发布前的 P0 功能规划中，计划是在侧边栏放置选项允许用户选择直接请求 / 通过server请求。

#### 代码

确实 v2 把代码拆分得比较细，也是为了能承载和维护好更多的功能。其实现在 v1 的大部分逻辑都集中在 `Generate.tsx` 中，已经开始不便阅读了。我们会在文档或贡献指南中尽量清楚地解释代码结构。

#### 历史会话管理

导入导出的功能会有，毕竟现在已经把所有数据都打包成 json 存在浏览器了，导出导入做起来不会太难；
至于其他有意思的玩法可能有一些取舍：
- 编辑对话做起来不难，但我觉得它可能打破了对话的概念，需要再考虑下要不要加。删除对话可能容易接受一些；
- 清除上下文会做成快捷键，其他快捷键包括新建对话、全局搜索、聚焦输入框；
- 会话存档和回溯不太理解，是指内容存储和删除近期对话+保留之前对话的意思么？我的看法是留一个删除功能就好了，应该不需要新增按钮了。

#### 社群

我认为社群还是需要解决知识共享的问题，比如把问题抛到群里后，在互联网是搜不到的，小圈子也不便于全球用户的参与。而且这种群聊方式还是不方便问题的持续跟进，不像 issue 一样能较长期地聚焦在某一个问题上。对于非 Bug Report / Feature Request 的纯提问类消息，使用 GitHub Discussions 也是方便的。
不过可能会考虑像其他开源社区一样建立 Discord 群组。

再次感谢建议！

**Comment by enhay** [comment]
> v2版本看起来还有不少兼容性的bug,目前测试只有chrome新版本是ok的，在coloros 13的手机自带浏览器，360急速，夸克等浏览器下 聊天区不显示，按钮也没反应。

版本要求太高了，一个dvh就至少要求chrome 101
