### ISSUE TITLE
Feat/v2  There is a cross-domain issue when using stable diffusion after generating the image.

### ISSUE THREAD

**Issue by TraderGalax** [ddiu8081/chatgpt-demo#371]
### Describe the bug

![139851681623409_ pic](https://user-images.githubusercontent.com/30950645/232273701-8b1f28c4-9028-490d-8963-ac08092f373f.jpg)

### Reproduction

There is a cross-domain issue when using stable diffusion after generating the image.

### System Info

```Shell
There is a cross-domain issue when using stable diffusion after generating the image.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
We are currently developing support for stable-diffusion. I'll let you know when it is completed.

**Comment by ddiu8081** [comment]
fixed. When stable-diffusion is selected, it will be requested via the backend.
