### ISSUE TITLE
Feat:v2 Add the function of sending messages by hitting enter.  ​

### ISSUE THREAD

**Issue by TraderGalax** [ddiu8081/chatgpt-demo#372]
### Clear and concise description of the problem

https://github.com/ddiu8081/chatgpt-demo/pull/370

### Suggested solution

https://github.com/ddiu8081/chatgpt-demo/pull/370
Feat:v2 Add the function of sending messages by hitting enter.

​

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Thanks for contributing! But in v2, I have some different ideas about the shortcut keys for sending messages.

I plan to provide a setting item to change the shortcut keys for sending messages. So sorry I can't merge your pull request directly.

**Comment by TraderGalax** [comment]
> Thanks for contributing! But in v2, I have some different ideas about the shortcut keys for sending messages.
> 
> I plan to provide a setting item to change the shortcut keys for sending messages. So sorry I can't merge your pull request directly.

Good design, looking forward to seeing it in the future
