### ISSUE TITLE
Feat/v2 Recommended to increase the display of code blocks

### ISSUE THREAD

**Issue by TraderGalax** [ddiu8081/chatgpt-demo#375]
### Clear and concise description of the problem

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/30950645/232759530-2ffb72a9-6750-4c79-947c-0342ff62478c.png">
Recommended to increase the display of code blocks

### Suggested solution

Recommended to increase the display of code blocks

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
We've added code block highlighting if ChatGPT is returned in standard markdown format, in commit https://github.com/ddiu8081/chatgpt-demo/commit/fc8a50a872f12cfde9efa707c65d9b4ca139f6d0.

In some cases, it does not seem to return in the standard format, resulting in not rendering the highlight, see case #205 . You can test if this is a common case.

![ScreenShot 2023-04-18 at 19 23 01@2x](https://user-images.githubusercontent.com/1998168/232762261-2de37fef-aed1-4682-9425-028332d7b378.png)
