### ISSUE TITLE
Inconsistency in Environment Variables Causing Sign Mechanism Failure

### ISSUE THREAD

**Issue by CNSeniorious000** [ddiu8081/chatgpt-demo#376]
### Describe the bug

The `.env.example` file includes a `SECRET_KEY` field that is used to generate signatures. However, during a reverse engineering process, I discovered that the third item of `${timestamp}:${lastMessage}:${secretKey}` is always undefined, regardless of the value of `end.SECRET_KEY`. Further investigation revealed that the issue is caused by the following line of code:

```ts
const secretKey = import.meta.env.PUBLIC_SECRET_KEY as string
```

This line of code retrieves the `PUBLIC_SECRET_KEY` key instead of the `SECRET_KEY` key, resulting in an incorrect value being used for the signature generation process.

This issue poses a security risk as it renders the sign mechanism of any website deployed using this repository ineffective. To address this issue, we recommend the following solutions.

There are two possible solutions to this issue:

Rename the key in `.env.example` to `PUBLIC_SECRET_KEY`, but this would require multiple changes throughout the repository, including the `README.md`.
Change the key's name in [this line](https://github.com/ddiu8081/chatgpt-demo/blob/main/src/utils/auth.ts#L20) to `SECRET_KEY`.
I personally recommend implementing the second solution.

### Reproduction

Deploy this repository and set SECRET_KEY to anything.

### System Info

```Shell
  System:
    OS: Linux5.4 OpenCloudOS 8.6
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 67.17 MB / 1.68 GB
    Container: Yes
    Shell 4.4.20 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Yes, this is indeed a bug. 
But the second solution is not available. `generateSignature` will be called both on client-side and server-side. All environment variables are available in server-side code, but only prefixed with `PUBLIC_` are available in client-side. Renaming it to `SECRET_KEY` will cause signature mismatch.
