### ISSUE TITLE
Feat/v2 I suggest adding voice input and output

### ISSUE THREAD

**Issue by TraderGalax** [ddiu8081/chatgpt-demo#382]
### Clear and concise description of the problem

Feat/v2 I suggest adding voice input and output

### Suggested solution

Feat/v2 I suggest adding voice input and output

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Duplicate of #228
