### ISSUE TITLE
通过docker方式安装完key也填写完报这个错误Invalid signature.

### ISSUE THREAD

**Issue by strengthen8** [ddiu8081/chatgpt-demo#384]
### Describe the bug

![image](https://user-images.githubusercontent.com/26496661/234135713-eb155771-6652-4808-b2e3-13ced7ff61c6.png)

### Reproduction

能正常使用

### System Info

```Shell
windows，谷歌浏览器
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhul-cloud** [comment]
遇到相同问题

**Comment by zhul-cloud** [comment]
@strengthen8  有什么解决方案吗？

**Comment by zhul-cloud** [comment]
@strengthen8  可以先把签名部分的代码注释掉，然后重新用docker build . -t ddiu8081/chatgpt-demo:latest命令编译，最后用docker run --name=chatgpt-demo -e OPENAI_API_KEY=xxxx -p 3000:3000 -d ddiu8081/chatgpt-demo:latest命令启动即可

**Comment by strengthen8** [comment]
已自行处理
