### ISSUE TITLE
本地修改了.env的OPENAI_API_KEY，为啥运行报错呢？

### ISSUE THREAD

**Issue by mango2017** [ddiu8081/chatgpt-demo#39]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.post (D:\new_phpstudy_pro\WWW\chatgpt-demo-main\src\pages\api\generate.ts:14:22)
    at async call (file:///D:/new_phpstudy_pro/WWW/chatgpt-demo-main/node_modules/astro/dist/core/endpoint/index.js:71:20)
    at async call (file:///D:/new_phpstudy_pro/WWW/chatgpt-demo-main/node_modules/astro/dist/core/endpoint/dev/index.js:15:10)
    at async handleRoute (file:///D:/new_phpstudy_pro/WWW/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/route.js:117:20)
    at async run (file:///D:/new_phpstudy_pro/WWW/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/request.js:46:14)
    at async runWithErrorHandling (file:///D:/new_phpstudy_pro/WWW/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///D:/new_phpstudy_pro/WWW/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:3)

  Cause:
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\new_phpstudy_pro\WWW\chatgpt-demo-main\node_modules\undici\lib\core\connect.js:182:24)
    at D:\new_phpstudy_pro\WWW\chatgpt-demo-main\node_modules\undici\lib\core\connect.js:129:46
    at Immediate._onImmediate (D:\new_phpstudy_pro\WWW\chatgpt-demo-main\node_modules\undici\lib\core\connect.js:168:33)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by iLazarus** [comment]
请使用命令测试
```
curl -X POST 'https://api.openai.com/v1/chat/completions' -H "Content-Type:application/json" -H "Authorization: Bearer 这段中文替换你自己的密钥" 
```

测试后继续反馈

**Comment by mango2017** [comment]
> 请使用命令测试
> 
> ```
> curl -X POST 'https://api.openai.com/v1/chat/completions' -H "Content-Type:application/json" -H "Authorization: Bearer 这段中文替换你自己的密钥" 
> ```
> 
> 测试后继续反馈

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (28) Failed to connect to api.openai.com port 443 after 21085 ms: Timed out

**Comment by quzard** [comment]
> > 请使用命令测试
> > ```
> > curl -X POST 'https://api.openai.com/v1/chat/completions' -H "Content-Type:application/json" -H "Authorization: Bearer 这段中文替换你自己的密钥" 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 测试后继续反馈
> 
> % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- 0:00:21 --:--:-- 0 curl: (28) Failed to connect to api.openai.com port 443 after 21085 ms: Timed out

被墙了，得配置代理

**Comment by iLazarus** [comment]
如你所见，你都连不上API

**Comment by mango2017** [comment]
那我需要怎么操作啊

**Comment by hqw567** [comment]
![image](https://user-images.githubusercontent.com/74847198/222675733-cec60260-c064-49fb-a625-bdaf08a0c94a.png)
这个错误呢？

**Comment by mango2017** [comment]
> > > 请使用命令测试
> > > ```
> > > curl -X POST 'https://api.openai.com/v1/chat/completions' -H "Content-Type:application/json" -H "Authorization: Bearer 这段中文替换你自己的密钥" 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 测试后继续反馈
> > 
> > 
> > % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- 0:00:21 --:--:-- 0 curl: (28) Failed to connect to api.openai.com port 443 after 21085 ms: Timed out
> 
> 被墙了，得配置代理

好的

**Comment by quzard** [comment]
> 那我需要怎么操作啊

# 方法1
使用clash for Windows的tun模式，接管docker流量

# 方法2
暂时可以用我的分支 https://github.com/quzard/chatgpt-demo ，加上了http代理支持

以clash for Windows为参考，开启clash for Windows的allow lan后设置HTTPS_PROXY=http://电脑ip:7890

**Comment by iLazarus** [comment]
> 

SNI or certificate check failed

**Comment by hqw567** [comment]
![image](https://user-images.githubusercontent.com/74847198/222678263-69099191-6b62-4aac-9560-60828ccf9b8e.png)
提示这个才有效吧

**Comment by iLazarus** [comment]
> ![image](https://user-images.githubusercontent.com/74847198/222678263-69099191-6b62-4aac-9560-60828ccf9b8e.png) 提示这个才有效吧

请求已经发出，但发生了请求错误，因为没带上BODY

```
curl -X POST 'https://api.openai.com/v1/chat/completions' -H "Content-Type:application/json" -H "Authorization: Bearer 这段中文替换你自己的密钥" -d '{"model": "gpt-3.5-turbo","messages":]{"role": "user", "content": "what's your name"}],"temperature":0.6,stream: true}'
```

**Comment by hqw567** [comment]
> > ![图像](https://user-images.githubusercontent.com/74847198/222678263-69099191-6b62-4aac-9560-60828ccf9b8e.png)提示这个才有效吧
> 
> 请请求已经发出，但发生了请求错误，因为没有带上BODY
> 
> ```
> curl -X POST 'https://api.openai.com/v1/chat/completions' -H "Content-Type:application/json" -H "Authorization: Bearer 这段中文替换你自己的密钥" -d '{"model": "gpt-3.5-turbo","messages":]{"role": "user", "content": "what's your name"}],"temperature":0.6,stream: true}'
> ```

这种提示已经可以正常使用了

**Comment by soutlu** [comment]
![image](https://user-images.githubusercontent.com/64189761/222680064-ddfe8802-6a5a-4827-aafd-def71aaf3682.png)
在wsl2中一点反应都没有

**Comment by iLazarus** [comment]
> ![image](https://user-images.githubusercontent.com/64189761/222680064-ddfe8802-6a5a-4827-aafd-def71aaf3682.png) 在wsl2中一点反应都没有

如果你在curl -v 加上了-v参数，基本上你看到你的请求定住了，为什么呢，因为你的网络

**Comment by OPenOneKun** [comment]
我把环境变量的文件名改成.env就好了

**Comment by OPenOneKun** [comment]
> > 我把环境变量的文件名改成.env就好了
> 
> 你curl不返回和你工程的.env配置没有任何关系

我的是有返回的，debug发现没有读取到环境变量中的apikey，项目中的.env文件名是.env.example 我改成.env就正常了

**Comment by soutlu** [comment]
![image](https://user-images.githubusercontent.com/64189761/222686311-f0fb9ad0-46e2-4d61-8c38-4959227a306d.png)
有大佬知道这个是什么原因吗

**Comment by rogepi** [comment]
我遇到了这个问题，Node版本v18.14.2
![image](https://user-images.githubusercontent.com/56425392/222691274-61f3957b-fb17-43e8-897e-cca18060830b.png)

**Comment by zhanhongzhu** [comment]
> 我遇到了这个问题，Node版本v18.14.2 ![image](https://user-images.githubusercontent.com/56425392/222691274-61f3957b-fb17-43e8-897e-cca18060830b.png)

我也是同样的问题

**Comment by yzh990918** [comment]
> > 我遇到了这个问题，Node版本v18.14.2 ![image](https://user-images.githubusercontent.com/56425392/222691274-61f3957b-fb17-43e8-897e-cca18060830b.png)
> 
> 我也是同样的问题

这种应该就是切到Node18，重新装下依赖就行，或者你本地nvm不是18

**Comment by ddiu8081** [comment]
Duplicate of #34

**Comment by ronalzhang** [comment]
{
  "errno": -61,
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 3000
}
大哥给看看这个是什么问题啊
