### ISSUE TITLE
vercel 部署发生错误

### ISSUE THREAD

**Issue by AndPuQing** [ddiu8081/chatgpt-demo#41]
![image](https://user-images.githubusercontent.com/27223114/222691762-9ac71a16-c2c9-4467-b056-4301b4024c2a.png)

**Comment by DawnMagnet** [comment]
我刚部署完是没问题的

**Comment by turbowars** [comment]
having the same issue while trying to deploy to vercel

**Comment by Emilstromberg** [comment]
This is a checkly specific error, I fixed mine by switching the runtime version to >20.02 on their website at /settings/account/runtimes
