### ISSUE TITLE
Automatically refresh when re-enter from background

### ISSUE THREAD

**Issue by Xueshen6** [ddiu8081/chatgpt-demo#42]
网页进入后台再进入会自动刷新，切程序什么的都会，用的docker部署。还有就是有时候，聊天过久会直接不回复

**Comment by ddiu8081** [comment]
自动刷新可以提供一个复现方法么；
聊天过久是因为 API 的字数限制，未来可能会提供一个错误说明。 #61

**Comment by Xueshen6** [comment]
> 自动刷新可以提供一个复现方法么；
> 聊天过久是因为 API 的字数限制，未来可能会提供一个错误说明。 #61

可以：Ubuntu+docker(made by quzard),配置好后ios客户端浏览器访问界面，正常使用。切出去回个微信，返回浏览器，会触发自动刷新

**Comment by cyio** [comment]
有两个场景：
1. 移动端浏览器切到后台，再切回前台页面刷新、
2. 开发模式，改完代码，开发服务刷新，状态丢失

可能本地得给缓存下聊天

**Comment by ddiu8081** [comment]
We have implemented the storage of history message.
