### ISSUE TITLE
一些反馈和需求

### ISSUE THREAD

**Issue by ggh200** [ddiu8081/chatgpt-demo#43]
#### 反馈
1. 输出内容很长的时候，滚动条不会自往下滚
2. 光标位置有问题，不能继续输入得点一下对话框

#### 功能需求
1. 能返回图片就好了
2. 可否增加一个自定义API的功能

**Comment by M1saka10010** [comment]
貌似当对话长度打到几千字左右，vercel就会出现504

**Comment by ddiu8081** [comment]
> 貌似当对话长度打到几千字左右，vercel就会出现504

目前 API 需要回传历史记录，超过 4096 tokens 就会失败，请先定时清理记录。

**Comment by M1saka10010** [comment]
> > 貌似当对话长度打到几千字左右，vercel就会出现504
> 
> 目前 API 需要回传历史记录，超过 4096 tokens 就会失败，请先定时清理记录。

哦哦，我还以为是vercel的限制，原来是官网的限制是4096啊，我原先还以为有个1w+的TAT

**Comment by ddiu8081** [comment]
Please submit one question at a time, listing multiple questions at the same time is not easy to manage.

Please resubmit if necessary, thanks.

**Comment by yuyebei** [comment]
> > 貌似当对话长度打到几千字左右，vercel就会出现504
> 
> 目前 API 需要回传历史记录，超过 4096 tokens 就会失败，请先定时清理记录。

请问怎么清理记录，只能删掉重来吗
