### ISSUE TITLE
代码块字体过小，整体页面宽度可以适当加宽

### ISSUE THREAD

**Issue by hyperty** [ddiu8081/chatgpt-demo#48]

**Comment by RyanBin0126** [comment]
这个可以直接在chatgpt-demo /src layouts/下的文件里修改width实现

**Comment by hyperty** [comment]
> 这个可以直接在chatgpt-demo/src/layouts/下的文件里修改width实现

牵一发动全身，改了width之后，对话框不能自适应地加宽，文字部分依然是原来的宽度排列在靠左的位置。好像用的是外部css，找不到可以修改的地方。另外代码块字体大小为0.875em，最优大小应该为1.25em🥲请大佬指点一下怎么修改

**Comment by RyanBin0126** [comment]
> > 这个可以直接在chatgpt-demo/src/layouts/下的文件里修改width实现
> 
> 牵一发动全身，改了width之后，对话框不能自适应地加宽，文字部分依然是原来的宽度排列在靠左的位置。好像用的是外部css，找不到可以修改的地方。另外代码块字体大小为0.875em，最优大小应该为1.25em🥲请大佬指点一下怎么修改

挺奇怪的，我这里修改width之后，文字部分是可以随着对话框宽度整体加宽的。
代码块字体不太清楚，理论上不应该是在chatgpt-demo/src/message.css里统一修改吗？

**Comment by hyperty** [comment]
在Layout.astro中修改max-width为100ch
`main {
		max-width: 100ch;
		margin: 0 auto;
		padding: 6rem 2rem 4rem;
	}`

并且在message.css中覆写
`.prose, [prose=""] {
  max-width: 84ch;
}

.message .hljs {
  background-color: transparent;
  font-size: 1.1em;
}`
可以更改对话框宽度，并且字体大小会稍大一些，看起来舒服一点
