### ISSUE TITLE
代码展示断开了

### ISSUE THREAD

**Issue by cyio** [ddiu8081/chatgpt-demo#51]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3146103/222856844-35ea0d0c-0c2f-4941-926c-28c8c269f3f8.png">

**Comment by ddiu8081** [comment]
由于回复的内容不是 markdown 代码格式，我们也没什么好办法去判断它是个代码，所以可能暂时不好解决。可以考虑换个问法？

**Comment by cyio** [comment]
确实是 openai 返回数据的问题，没有 code 标记
