### ISSUE TITLE
请问这个项目能build吗？

### ISSUE THREAD

**Issue by hswmartin** [ddiu8081/chatgpt-demo#52]
请问有人build成功了吗？运行run build，有几个warning,但是看不到dist文件夹

**Comment by cuicui-V5** [comment]
https://docs.astro.build/zh-cn/guides/deploy/

**Comment by blkcor** [comment]
因为使用vercel部署的 vercel会自动执行一些edge function，dist会作为中间产物生成，最终会生成一个vercel目录

**Comment by hieiip1203** [comment]
我没成功

**Comment by ninvfeng** [comment]
本地build可以看这个
https://docs.astro.build/zh-cn/guides/integrations-guide/node/

安装
npx astro add node
npm install @astrojs/node

启动
node ./dist/server/entry.mjs

**Comment by lxxxv5** [comment]
> 本地build可以看这个 https://docs.astro.build/zh-cn/guides/integrations-guide/node/
> 
> 安装 npx astro add node npm install @astrojs/node
> 
> 启动 node ./dist/server/entry.mjs

本地启动后开始对话，看到 /api/generate 接口一直在 pending 是怎么回事啊

**Comment by appsdog** [comment]
在centos上部署很复杂啊。

设置和安装依赖项npm i
制作一个副本.env.example，然后将其重命名为.env

添加到.env   OPENAI_API_KEY=sk-xxx...
运行应用  npm run dev

这四步成功了，打开网站，403

**Comment by ninvfeng** [comment]
> > 本地build可以看这个 https://docs.astro.build/zh-cn/guides/integrations-guide/node/
> > 安装 npx astro add node npm install @astrojs/node
> > 启动 node ./dist/server/entry.mjs
> 
> 本地启动后开始对话，看到 /api/generate 接口一直在 pending 是怎么回事啊

估计是接口地址被屏蔽了 curl https://api.openai.com 看下, 如果一直pending就是被qiang了

**Comment by ddiu8081** [comment]
现在默认的 build 模式已经改为了 `node`，可以 build 后使用 `node ./dist/server/entry.mjs` 运行。

**Comment by ddiu8081** [comment]
> > > > 本地build可以看这个 https://docs.astro.build/zh-cn/guides/integrations-guide/node/
> > > > 安装 npx astro add node npm install @astrojs/node
> > > > 启动 node ./dist/server/entry.mjs
> > > 
> > > 
> > > 本地启动后开始对话，看到 /api/generate 接口一直在 pending 是怎么回事啊
> > 
> > 
> > 估计是接口地址被屏蔽了 curl https://api.openai.com 看下, 如果一直pending就是被qiang了
> 
> 被墙了怎么处理呢

本地运行的话，可以使用 `HTTPS_PROXY` 变量，为 OpenAI 接口指定一个 HTTP 代理。

**Comment by web256** [comment]
HOST=0.0.0.0  PORT=80 node ./dist/server/entry.mjs  
访问 /api/generate 接口 500 这个错误日志在哪看？
