### ISSUE TITLE
在centos上部署很复杂啊。403

### ISSUE THREAD

**Issue by appsdog** [ddiu8081/chatgpt-demo#55]
在centos上部署很复杂啊。

设置和安装依赖项npm i
制作一个副本.env.example，然后将其重命名为.env

添加到.env   OPENAI_API_KEY=sk-xxx...
运行应用  npm run dev

这四步成功了，打开网站，403

不合适小白一键部署，大佬出个完整教程吧，在centos上部署。

**Comment by curly210102** [comment]
你可以试试看用 Docker https://github.com/ddiu8081/chatgpt-demo/issues/1#issuecomment-1451651317
或者直接去 Vercel 一键部署，做下域名映射速度足够 https://github.com/ddiu8081/chatgpt-demo#deploy-with-vercel

**Comment by ddiu8081** [comment]
move to #72
