### ISSUE TITLE
-bash: ./dist/server/entry.mjs: No such file or directory

### ISSUE THREAD

**Issue by appsdog** [ddiu8081/chatgpt-demo#56]
root@ # ./dist/server/entry.mjs
-bash: ./dist/server/entry.mjs: No such file or directory

**Comment by curly210102** [comment]
Which script did you execute to generate the site? `npm run dev`, `npm run build` or others?
What kind of deployment are you trying?

**Comment by curly210102** [comment]
上下文是啥？和https://github.com/ddiu8081/chatgpt-demo/issues/56有关系吗？

**Comment by curly210102** [comment]
是想 build 出静态资源？可以看下这个 https://github.com/ddiu8081/chatgpt-demo/issues/52#issuecomment-1454365948
