### ISSUE TITLE
Hope the front end can add an exception handling mechanism

### ISSUE THREAD

**Issue by M1saka10010** [ddiu8081/chatgpt-demo#61]
### Clear and concise description of the problem

The front end will always show that the AI is Thinking instead of throwing an exception that exceeds the length limit. This interaction can easily confuse users.

### Suggested solution

Determine whether the message length exceeds the limit, or handle the error message returned by openai.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
We've just added a more detailed error message output. You should now be able to see the cause of the error in the UI.
