### ISSUE TITLE
[Feature Request] Multi chat support

### ISSUE THREAD

**Issue by wangyunjeff** [ddiu8081/chatgpt-demo#63]
### Clear and concise description of the problem

增加类似官网的new chat功能，有个侧边栏可以保留历史聊天记录。

### Suggested solution

增加类似官网的new chat功能，有个侧边栏可以保留历史聊天记录。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Added in v2.
