### ISSUE TITLE
运行时，显示报错。When running, an error is displayed.

### ISSUE THREAD

**Issue by Sweets-Sheep** [ddiu8081/chatgpt-demo#68]
### Describe the bug

error！How do I fix it?
![image](https://user-images.githubusercontent.com/111367588/222904018-56a1b306-5b28-46b1-8a3b-6c24538eac1c.png)
![image](https://user-images.githubusercontent.com/111367588/222904217-1e557a33-d734-4554-8bdb-5723ce91a41d.png)

### Reproduction

error

### System Info

```Shell
Cause {   "errno": -4078,   "code": "ECONNREFUSED",   "syscall": "connect",   "address": "127.0.0.1",   "port": 7890 }
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
When specified `HTTPS_PROXY`, you must have the http proxy enabled on the corresponding port (e.g. `7890`).
