### ISSUE TITLE
 Add a copy button to the code block

### ISSUE THREAD

**Issue by fangyuan99** [ddiu8081/chatgpt-demo#69]
### Clear and concise description of the problem

Add a copy button to the top right corner of the code block

### Suggested solution

#  Add a copy button to the code block
When used on the official website, the code block has a copy button, hoping to add this function

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by farfarbiao** [comment]
我也刚需这个功能
