### ISSUE TITLE
宝塔node项目新建里部署，端口填写错误 502

### ISSUE THREAD

**Issue by appsdog** [ddiu8081/chatgpt-demo#70]
宝塔node项目新建里部署，端口填写错误 502。     这个项目正确端口应该是多少？

**Comment by appsdog** [comment]
宝塔node项目启动。就自动停止 502.   【项目端口】：错误的端口会导致访问502，若不知道端口，可先随意填写，启动项目后再改为正确端口

**Comment by appsdog** [comment]
【项目端口】：错误的端口会导致访问502，若不知道端口，可先随意填写，启动项目后再改为正确端口

**Comment by ddiu8081** [comment]
`3000`

**Comment by appsdog** [comment]
![gpt宝塔](https://user-images.githubusercontent.com/125454476/222935330-fb3ea504-29c4-4d71-a346-e24a9f71cf0f.jpg)
一启动就自动停止。奇怪了

**Comment by appsdog** [comment]
node.js版本换成18. 启动失败  启动失败
> novel-gpt@0.0.1 dev > astro dev > novel-gpt@0.0.1 dev > astro dev > novel-gpt@0.0.1 dev > astro dev > novel-gpt@0.0.1 dev > astro dev > novel-gpt@0.0.1 dev > astro dev

**Comment by Teemwu** [comment]
遇到同样情况，修改 `astro.config.mjs` 文件后解决：

```js
// https://astro.build/config
export default defineConfig({
  // 增加
  server: {
    host: '0.0.0.0',
    port: 5566
  },
// ...
```
