### ISSUE TITLE
[Feature Request] Light mode

### ISSUE THREAD

**Issue by kollyQAQ** [ddiu8081/chatgpt-demo#71]
### Clear and concise description of the problem

希望能跟ChatGPT 一样有深浅主题模式切换，现在的夜间模式白天看不太清楚

### Suggested solution

希望能跟ChatGPT 一样有深浅主题模式切换，现在的夜间模式白天看不太清楚

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by cyio** [comment]
hope it defaults to light mode
