### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by ddy-ddy** [ddiu8081/chatgpt-demo#76]
作者的工作真的做的很棒！

访问作者贴出的demo链接，发现回答的速度特别快以及回答的内容都是完整的（chatgpt网页版总是会限制每次回答的字数）

想请问下作者哪些因素和技术决定了回答的速度和回答的内容字数呢？

还有作者的demo链接用的是您自己的api key吗，这样大家都可以访问的话，18美元的免费额度是不是很快就会用完呀😂

**Comment by ddiu8081** [comment]
https://platform.openai.com/docs/guides/chat

- 主要取决于 API 的调用速度且没有手动限速（ChatGPT Free 似乎有限速但不确定），API 直接调用就是很快的；
- 选用的 model、以及调用的网络状况都有可能影响；
- 内容最大字数受 API 的 token 数限制（可以理解为字数），目前限制大概为 一轮对话的所有提问+回答总 token 数为 4096；
- 目前 Demo 站点用的是个人 API key，是付费账号但后期还是需要防滥用
