### ISSUE TITLE
在长回答过程中滚动页面, 页面有概率触发鬼畜抖动

### ISSUE THREAD

**Issue by ninvfeng** [ddiu8081/chatgpt-demo#89]
### Describe the bug

在回答过程中滚动页面, 页面有概率触发鬼畜抖动
是不是可以在用户滚动的时候, 关掉自动滚动 😊

### Reproduction

提问: python教程 然后滚动查看页面

### System Info

```Shell
OS: macOS 12.3.1
Chrome: 110.0.5481.177
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XOKP** [comment]
回答中存在存在长代码的时候，几乎每次都会发生

**Comment by ggh200** [comment]
+1，严重抖动

**Comment by yishuiwang** [comment]
chatpgt也是有这个问题，不过不是很剧烈，但是这个就比较鬼畜了

**Comment by ithou** [comment]
+1 手机Chrome体验明显。

**Comment by yesmore** [comment]
我是监听用户鼠标滚动/键盘上下按键/手势touchmove这几个事件就暂停自动滚动，体验还行 ([这里](https://github.com/yesmore/QA/blob/eeb472e2bc350777f4538a60ea24b2c8508b716d/src/components/Generator.tsx#L26))

**Comment by M1saka10010** [comment]
+1，严重抖动

**Comment by nevertoday** [comment]
请问， 我本机docker 达不到demo 的速度， 请问我是不是要买一台服务器好一点？ 
还有哪位大神可以指导我，我需要购买国内还是国外的服务器？ 国内的不欧克？

**Comment by M1saka10010** [comment]
> 请问， 我本机docker 达不到demo 的速度， 请问我是不是要买一台服务器好一点？ 还有哪位大神可以指导我，我需要购买国内还是国外的服务器？ 国内的不欧克？

可能是你代理速度不佳导致的

**Comment by nevertoday** [comment]
很有可能！
