### ISSUE TITLE
System Role button

### ISSUE THREAD

**Issue by llegomark** [ddiu8081/chatgpt-demo#97]
### Describe the bug

In the event that I click on the System Role button but choose not to provide any input in the textbox, it would be beneficial to have the option to close the dialogue box without requiring any input.

### Reproduction

Click the Add System Role button

### System Info

```Shell
NA
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Currently, when you click the "Set" button without entering anything, the role is not set. Can this be misunderstood?
