### ISSUE TITLE
希望添加个连接数据库

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#99]
### Clear and concise description of the problem

进行用户管理制度，可以查看用户的问题，访问，使用情况，进行封禁，限制等管理

### Suggested solution

可以查看用户的问题，访问，使用情况，进行封禁，限制等管理

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by hyperty** [comment]
不太可能会加，加了你们就要拿去商用。

**Comment by ddiu8081** [comment]
这不太符合项目的初衷了，且它本身没有用户的概念，做的话会改动非常大；当然如果感兴趣的话，可以在 MIT 基础上做二次开发。
